# Copyright (C) 2025-2026 Steel Security Advisors LLC
# SPDX-License-Identifier: Apache-2.0
"""INVARIANT-36 — no third-party cryptographic implementation in the validation path.

``tools/check_corpus_originality.py`` enforces that AMA's correctness is measured
against published specifications and against its own reference encoder, never
against another cryptographic product. These tests pin both directions: the
repository passes today, and each class of violation is reproduced and required
to be caught.

The invariant exists because the repository failed it once. The key-format
conformance corpus carried twelve PEM files generated by OpenSSL, vendored as
the answer key for EC PKCS#8 and SPKI because RFC 5915 and RFC 5480 publish no
worked examples. Nothing linked or invoked OpenSSL at build or run time — but a
competing implementation's output was the thing AMA's correctness was measured
against, inside AMA's own repository, in a project whose stated position is that
it depends on no other cryptographic implementation.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOL_PATH = REPO_ROOT / "tools" / "check_corpus_originality.py"


def _load_tool() -> ModuleType:
    spec = importlib.util.spec_from_file_location("check_corpus_originality", TOOL_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def tool() -> ModuleType:
    return _load_tool()


# ---------------------------------------------------------------------------
# The anchor
# ---------------------------------------------------------------------------
def test_the_repository_holds_the_invariant(tool: ModuleType) -> None:
    assert tool.scan_for_binary_invocations() == []
    assert tool.scan_corpus_sources() == []
    assert tool.check_reference_encoder() == []


def test_the_cli_reports_success(tool: ModuleType) -> None:
    assert tool.main() == 0


def test_no_openssl_key_material_remains_anywhere_in_the_corpus() -> None:
    """The specific thing that was removed, asserted by name.

    Stated as its own test rather than folded into the generic scan, because
    this is the finding a reviewer will want to be able to point at.
    """
    corpus = REPO_ROOT / "tests" / "kat" / "keyformats"
    assert not (corpus / "openssl").exists(), (
        "the OpenSSL key corpus is back; RFC 9500 §2.3 publishes the EC keys it "
        "was standing in for"
    )
    for path in corpus.rglob("*"):
        assert path.suffix != ".pem", (
            f"{path} is a loose PEM file. Every vendored record lives in a JSON "
            "file that names the document it came from."
        )


def test_every_corpus_file_cites_an_rfc(tool: ModuleType) -> None:
    corpus = REPO_ROOT / "tests" / "kat" / "keyformats"
    seen = 0
    for path in sorted(corpus.glob("*.json")):
        source = json.loads(path.read_text())["source"]
        assert any(host in source["url"] for host in tool.STANDARDS_HOSTS), path.name
        assert source["title"] and source["revision"], path.name
        seen += 1
    assert seen >= 5, f"only {seen} corpus files found; the scan is not resolving"


# ---------------------------------------------------------------------------
# Failure directions
# ---------------------------------------------------------------------------
def test_a_subprocess_invocation_of_openssl_is_caught(tool: ModuleType, tmp_path: Path) -> None:
    """The exact shape the removed generator used."""
    (tmp_path / "tools").mkdir()
    (tmp_path / "tools" / "gen.py").write_text(
        "import subprocess\n"
        'subprocess.run(["openssl", "genpkey", "-algorithm", "EC"], check=True)\n'
    )
    problems = tool.scan_for_binary_invocations(tmp_path)
    assert any("openssl" in p and "gen.py" in p for p in problems), problems


@pytest.mark.parametrize("binary", ["gpg", "certtool", "keytool", "certutil"])
def test_other_cryptographic_binaries_are_caught(
    tool: ModuleType, tmp_path: Path, binary: str
) -> None:
    """Not an OpenSSL-shaped rule: any other implementation counts."""
    (tmp_path / "tests").mkdir()
    (tmp_path / "tests" / "t.py").write_text(
        f'import subprocess\nsubprocess.check_output("{binary} --version", shell=True)\n'
    )
    problems = tool.scan_for_binary_invocations(tmp_path)
    assert any(binary in p for p in problems), problems


def test_the_shipped_package_is_in_scope(tool: ModuleType, tmp_path: Path) -> None:
    """INVARIANT-1's strongest clause is about the shipped package, not the tests.

    ``legacy_compat.py`` shelled out to ``openssl ts`` to build and verify
    RFC 3161 timestamps — a competing implementation performing a cryptographic
    operation inside AMA at *runtime*, which is what INVARIANT-1 forbids in as
    many words. The scan originally covered ``tests/`` and ``tools/`` only and
    recorded that as an exception in its docstring. The exception is gone and
    so is the blind spot; this is what keeps it gone.
    """
    assert "ama_cryptography" in tool.SCAN_ROOTS, (
        "the shipped package must be scanned — it carries the strongest form of " "the rule"
    )
    (tmp_path / "ama_cryptography").mkdir()
    (tmp_path / "ama_cryptography" / "legacy_compat.py").write_text(
        "import subprocess\n"
        'subprocess.run(["openssl", "ts", "-query", "-data", "-"], capture_output=True)\n'
    )
    problems = tool.scan_for_binary_invocations(tmp_path)
    assert any("openssl" in p and "legacy_compat.py" in p for p in problems), problems


def test_the_real_package_invokes_no_cryptographic_binary(tool: ModuleType) -> None:
    """The live tree, not a fixture. This is the assertion that would have
    failed before the RFC 3161 work and must never fail again."""
    problems = [p for p in tool.scan_for_binary_invocations() if "ama_cryptography" in p]
    assert problems == [], problems


def test_a_mention_in_prose_is_not_a_finding(tool: ModuleType, tmp_path: Path) -> None:
    """This tree is full of "replaces OpenSSL X" comments — they are originality
    *claims*, and flagging them would make the gate un-satisfiable and push a
    maintainer to delete accurate documentation."""
    (tmp_path / "tools").mkdir()
    (tmp_path / "tools" / "note.py").write_text(
        '"""Replaces OpenSSL EVP_Digest; no openssl dependency."""\n'
        "# openssl is not used here\n"
        'OPENSSL_NOTE = "openssl"\n'
        "import subprocess\n"
        'subprocess.run(["python3", "-c", "pass"], check=True)\n'
    )
    assert tool.scan_for_binary_invocations(tmp_path) == []


def test_a_corpus_file_citing_a_non_standards_source_is_caught(
    tool: ModuleType, tmp_path: Path
) -> None:
    corpus = tmp_path / "keyformats"
    corpus.mkdir()
    (corpus / "vendor.json").write_text(
        json.dumps(
            {
                "source": {"url": "https://example.com/keys", "title": "t", "revision": "r"},
                "records": [],
            }
        )
    )
    problems = tool.scan_corpus_sources(corpus)
    assert any("not a standards-body archive" in p for p in problems), problems


def test_a_directory_of_key_files_in_the_corpus_is_caught(tool: ModuleType, tmp_path: Path) -> None:
    """How the third-party material was carried, so it is caught structurally
    and not only by the URL check."""
    corpus = tmp_path / "keyformats"
    (corpus / "somevendor").mkdir(parents=True)
    (corpus / "ok.json").write_text(
        json.dumps(
            {
                "source": {
                    "url": "https://www.rfc-editor.org/rfc/rfc9500.txt",
                    "title": "t",
                    "revision": "r",
                },
                "records": [],
            }
        )
    )
    # Deliberately *not* a literal PEM header: the check under test keys off
    # the directory, not the contents, and a real header here would be a finding
    # for tools/check_secrets.py (INVARIANT-23) in this very file.
    (corpus / "somevendor" / "P-256.key.pem").write_text("placeholder\n")
    problems = tool.scan_corpus_sources(corpus)
    assert any("unexpected directory" in p for p in problems), problems


def test_a_reference_encoder_that_imports_the_production_one_is_caught(
    tool: ModuleType, tmp_path: Path
) -> None:
    """The one-line change that would silently void every differential test."""
    path = tmp_path / "ref.py"
    path.write_text("from ama_cryptography._asn1 import der_sequence\n")
    problems = tool.check_reference_encoder(path)
    assert any("imports ama_cryptography" in p for p in problems), problems

    path.write_text("import ama_cryptography.key_formats as kf\n")
    assert tool.check_reference_encoder(path) != []


def test_a_missing_reference_encoder_is_a_failure(tool: ModuleType, tmp_path: Path) -> None:
    """Fail closed: the reference is what replaced the third-party corpus, so
    its absence must not read as everything being fine."""
    assert tool.check_reference_encoder(tmp_path / "gone.py") != []


# ---------------------------------------------------------------------------
# Evasion shapes the scan used to miss
#
# Every one of these passed cleanly before, including — the one that matters —
# the exact spelling the *removed* code used: `cmd_query = ["openssl", "ts",
# ...]` assigned to a local and then handed to `subprocess.run`. A gate that
# would not have caught the code it exists to prevent returning is not a gate,
# so each shape gets a named negative control here.
# ---------------------------------------------------------------------------
@pytest.mark.parametrize(
    ("label", "source"),
    [
        (
            "list bound to a name — the shape the removed generator used",
            'import subprocess\nCMD = ["openssl", "genpkey", "-algorithm", "ed25519"]\n'
            "subprocess.run(CMD, check=True)\n",
        ),
        (
            "os.popen — the sibling of os.system, which was already covered",
            'import os\nos.popen("openssl genpkey -algorithm ed25519")\n',
        ),
        (
            "subprocess.getoutput",
            'import subprocess\nsubprocess.getoutput("openssl version")\n',
        ),
        (
            "os.execvp",
            'import os\nos.execvp("openssl", ["openssl", "version"])\n',
        ),
        (
            "a command string bound to a name and shelled out",
            'import os\nCMD = "openssl ts -query -data f -sha256"\nos.system(CMD)\n',
        ),
    ],
)
def test_indirect_invocations_are_caught(
    tool: ModuleType, tmp_path: Path, label: str, source: str
) -> None:
    (tmp_path / "ama_cryptography").mkdir()
    (tmp_path / "ama_cryptography" / "sneaky.py").write_text(source)
    problems = tool.scan_for_binary_invocations(tmp_path)
    assert any("openssl" in p for p in problems), f"{label}: {problems}"


def test_a_binary_name_that_only_appears_in_a_docstring_is_still_not_a_finding(
    tool: ModuleType, tmp_path: Path
) -> None:
    """The relaxation must not swing the other way.

    Resolving name bindings widens what the scan sees, so it has to keep *not*
    firing on the many comments in this repository of the form "replaces
    OpenSSL X" — including one bound to a module-level string.
    """
    (tmp_path / "ama_cryptography").mkdir()
    (tmp_path / "ama_cryptography" / "prose.py").write_text(
        "import subprocess\n"
        'NOTE = "this replaces the openssl ts -query call"\n'
        '"""Module docstring mentioning openssl and gpg."""\n'
        'subprocess.run(["python3", "-c", "pass"], check=True)\n'
    )
    assert tool.scan_for_binary_invocations(tmp_path) == []


class TestVectorGeneratorsComputeNothing:
    """A "NIST vector" must come from NIST, not from whatever hashed it.

    ``nist_vectors/fetch_vectors.py`` wrote ``SHA-256-FIPS180-4.json`` with
    ``"source": "FIPS 180-4 Section B.1"`` and every digest in it produced by
    ``hashlib.sha256(...).hexdigest()`` at generation time, while
    ``nist_vectors/run_vectors.py`` validated AMA's SHA-256 against that file.
    On any libcrypto-linked CPython — every manylinux wheel and every
    mainstream distribution Python, as ``tools/check_stdlib_hash_boundary.py``
    states — ``hashlib.sha256`` IS OpenSSL, so every regeneration would have
    replaced the specification's vectors with OpenSSL's output under the
    specification's name.  The committed values were correct; the source the
    next regeneration would draw from was not.

    The scan reads the GENERATORS, not the JSON: a digest sitting in a
    committed file carries no evidence of where it came from, which is exactly
    how this survived a gate whose stated subject is that question.
    """

    @staticmethod
    def _generator(tmp_path: Path, body: str) -> Path:
        directory = tmp_path / "nist_vectors"
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "fetch_vectors.py").write_text(body, encoding="utf-8")
        return tmp_path

    @pytest.mark.parametrize(
        "body,label",
        [
            ('import hashlib\nD = hashlib.sha256(b"abc").hexdigest()\n', "plain call"),
            ('D = __import__("hashlib").sha256(b"abc").hexdigest()\n', "__import__ call"),
            ("import hashlib\n", "a bare import, with no call at all"),
            ("from hashlib import sha256\n", "a from-import"),
            ('import hmac\nD = hmac.new(b"k", b"m").hexdigest()\n', "hmac"),
            ('import hashlib\nD = hashlib.new("sha256", b"abc").hexdigest()\n', "hashlib.new"),
        ],
    )
    def test_a_stdlib_digest_in_a_generator_is_reported(
        self, tool: ModuleType, tmp_path: Path, body: str, label: str
    ) -> None:
        problems = tool.scan_vector_generators(self._generator(tmp_path, body))
        assert problems, f"accepted {label}"

    def test_a_transcribing_generator_passes(self, tool: ModuleType, tmp_path: Path) -> None:
        body = (
            "import json\n"
            "# FIPS 180-4 Appendix B.1, transcribed.\n"
            'D = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"\n'
        )
        assert tool.scan_vector_generators(self._generator(tmp_path, body)) == []

    def test_an_empty_scope_fails_closed(self, tool: ModuleType, tmp_path: Path) -> None:
        problems = tool.scan_vector_generators(tmp_path)
        assert problems and "examined nothing" in problems[0]

    def test_the_repository_generators_are_clean(self, tool: ModuleType) -> None:
        assert tool.scan_vector_generators() == []

    def test_the_committed_sha256_vectors_are_the_published_ones(self) -> None:
        """The values themselves, checked against FIPS 180-4 by transcription.

        Independent of the gate: the gate says where the numbers may come
        from, this says they are the right numbers.  Both digests below appear
        in FIPS 180-4 Appendix B.1 and B.2; the empty-string digest is the
        NIST CAVP SHAVS ShortMsg Len=0 value.
        """
        path = REPO_ROOT / "nist_vectors" / "SHA-256-FIPS180-4.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        digests = {t["msg"]: t["md"] for g in data["testGroups"] for t in g["tests"]}
        assert digests["616263"] == (
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        )
        assert digests[""] == ("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")
        long_msg = next(k for k in digests if len(k) > 100)
        assert digests[long_msg] == (
            "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"
        )
