# Copyright (C) 2025-2026 Steel Security Advisors LLC
# SPDX-License-Identifier: Apache-2.0
"""The committed Ed25519 tables are exactly what the generator produces.

``src/c/internal/ama_ed25519_tables.h`` is generated by
``tools/gen_ed25519_tables.py`` from RFC 8032's curve constants alone.  This
regenerates it in memory and compares byte for byte, so an edit to the header
that bypassed the generator, or a generator change that was not committed
alongside its output, fails here.  ``tests/c/test_ed25519_static_tables.c``
checks the other direction — that every entry is the group element it claims
to be — against the library's variable-base arithmetic.
"""

from __future__ import annotations

import re

from tools import gen_ed25519_tables as gen


def test_header_matches_generator_byte_for_byte() -> None:
    assert gen.HEADER_PATH.is_file(), gen.HEADER_PATH
    committed = gen.HEADER_PATH.read_bytes().decode("utf-8")
    assert committed == gen.render()


def test_header_declares_the_geometry_the_generator_used() -> None:
    text = gen.HEADER_PATH.read_text(encoding="utf-8")

    def macro(name: str) -> int:
        match = re.search(rf"#define {name}\s+(\d+)", text)
        assert match is not None, name
        return int(match.group(1))

    assert macro("AMA_ED25519_COMB_WINDOW") == gen.COMB_WINDOW
    assert macro("AMA_ED25519_COMB_STRIDE_BITS") == 2 * gen.COMB_WINDOW
    assert macro("AMA_ED25519_COMB_ENTRIES") == 1 << (gen.COMB_WINDOW - 1)
    assert macro("AMA_ED25519_COMB_DIGITS") == gen.COMB_DIGITS
    assert macro("AMA_ED25519_COMB_TABLES") == gen.COMB_TABLES
    assert macro("AMA_ED25519_BASE_ODD_WINDOW") == gen.ODD_WINDOW
    assert macro("AMA_ED25519_BASE_ODD_COUNT") == 1 << (gen.ODD_WINDOW - 2)
    # The digit count covers a 256-bit scalar and the tables cover the digits.
    assert gen.COMB_DIGITS * gen.COMB_WINDOW >= 256
    assert 2 * gen.COMB_TABLES >= gen.COMB_DIGITS


def test_generator_arithmetic_is_the_rfc_8032_curve() -> None:
    """The generator's own curve law, checked against the standard's anchors."""
    b = gen.base_point()
    assert b[1] == (4 * pow(5, -1, gen.P)) % gen.P
    assert b[0] % 2 == 0
    assert gen.on_curve(b)
    # RFC 8032 §7.1 test 1: the public key is [a]B for the clamped seed hash.
    import hashlib

    seed = bytes.fromhex("9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60")
    a = bytearray(hashlib.sha512(seed).digest()[:32])
    a[0] &= 248
    a[31] &= 127
    a[31] |= 64
    x, y = gen.point_mul(int.from_bytes(a, "little"), b)
    encoded = (y | ((x & 1) << 255)).to_bytes(32, "little")
    assert encoded.hex() == "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a"
    # The tables are built from a point of order l.
    assert gen.point_mul(gen.L, b) == (0, 1)


def test_check_mode_reports_a_stale_header(tmp_path: object) -> None:
    """Negative control: --check must fail on a header that differs."""
    from pathlib import Path

    assert isinstance(tmp_path, Path)
    stale = tmp_path / "stale.h"
    stale.write_text(gen.render().replace("0x", "0X", 1), encoding="utf-8", newline="")
    assert gen.main(["--check", "--output", str(stale)]) == 1
    fresh = tmp_path / "fresh.h"
    assert gen.main(["--write", "--output", str(fresh)]) == 0
    assert gen.main(["--check", "--output", str(fresh)]) == 0
