/* Copyright (C) 2025-2026 Steel Security Advisors LLC */
/* SPDX-License-Identifier: Apache-2.0 */
/**
 * @file test_ed25519_static_tables.c
 * @brief Every entry of the static Ed25519 base-point tables is the group
 *        element it claims to be.
 *
 * src/c/internal/ama_ed25519_tables.h is generated by
 * tools/gen_ed25519_tables.py in two radices, and both instantiations of the
 * group arithmetic read it.  tests/test_ed25519_static_tables.py proves the
 * header is the generator's output; this test proves the generator's output
 * is right, by an independent route: each table entry, recovered from its
 * Niels form through the test-only export ama_ed25519_test_table_entry, must
 * equal [k]B computed by the library's variable-base wNAF ladder from the
 * RFC 8032 §5.1.4 compressed base point — a path that never touches the
 * comb table.  Both radices are checked when the build carries both.
 *
 *   comb[i][j] == (j + 1) * 2^(STRIDE * i) * B      for every i, j
 *   odd[i]     == (2 i + 1) * B                     for every i
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "ama_cryptography.h"
#include "../../src/c/internal/ama_testing_exports.h"

/* Ed25519 base point in compressed form (RFC 8032 §5.1.4): y = 4/5, x even. */
static const uint8_t base_compressed[32] = {
    0x58, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66,
    0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66,
    0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66,
    0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66,
};

/* scalar = value << shift_bits as a 64-byte little-endian integer, reduced mod
 * l through the library's own reducer so the wNAF ladder receives a 32-byte
 * scalar.  value < 2^8 and shift_bits < 504 keep it inside 64 bytes. */
static void shifted_scalar(uint8_t out[32], unsigned value, unsigned shift_bits) {
    uint8_t wide[64];
    unsigned byte = shift_bits / 8;
    unsigned bit = shift_bits % 8;
    unsigned v = value << bit;
    memset(wide, 0, sizeof wide);
    wide[byte] = (uint8_t)(v & 0xff);
    wide[byte + 1] = (uint8_t)((v >> 8) & 0xff);
    ama_ed25519_sc_reduce(wide);
    memcpy(out, wide, 32);
}

static int check_backend(int backend, const char *name) {
    int tables, entries, stride, odd_count, odd_shift;
    int i, j;
    int failures = 0;
    int compared = 0;
    uint8_t got[32], want[32], scalar[32];

    if (ama_ed25519_test_table_geometry(backend, &tables, &entries, &stride, &odd_count,
                                        &odd_shift) != 0) {
        printf("  %s: not compiled into this build — skipped\n", name);
        return 0;
    }
    printf("  %s: comb %d x %d (stride %d bits), %d odd multiples\n",
           name, tables, entries, stride, odd_count);

    for (i = 0; i < tables; i++) {
        for (j = 0; j < entries; j++) {
            if (ama_ed25519_test_table_entry(backend, 0, i, j, got) != 0) {
                fprintf(stderr, "  FAIL %s comb[%d][%d]: export refused\n", name, i, j);
                failures++;
                continue;
            }
            shifted_scalar(scalar, (unsigned)(j + 1), (unsigned)(stride * i));
            if (ama_ed25519_scalarmult_public(want, scalar, base_compressed) != AMA_SUCCESS) {
                fprintf(stderr, "  FAIL %s comb[%d][%d]: reference scalarmult refused\n", name, i, j);
                failures++;
                continue;
            }
            compared++;
            if (memcmp(got, want, 32) != 0) {
                fprintf(stderr, "  FAIL %s comb[%d][%d] != (%d) * 2^%d * B\n",
                        name, i, j, j + 1, stride * i);
                failures++;
            }
        }
    }
    for (i = 0; i < odd_count; i++) {
        if (ama_ed25519_test_table_entry(backend, 1, i, 0, got) != 0) {
            fprintf(stderr, "  FAIL %s odd[%d]: export refused\n", name, i);
            failures++;
            continue;
        }
        shifted_scalar(scalar, (unsigned)(2 * i + 1), 0);
        if (ama_ed25519_scalarmult_public(want, scalar, base_compressed) != AMA_SUCCESS) {
            fprintf(stderr, "  FAIL %s odd[%d]: reference scalarmult refused\n", name, i);
            failures++;
            continue;
        }
        compared++;
        if (memcmp(got, want, 32) != 0) {
            fprintf(stderr, "  FAIL %s odd[%d] != %d * B\n", name, i, 2 * i + 1);
            failures++;
        }
    }
    for (i = 0; i < odd_count; i++) {
        if (ama_ed25519_test_table_entry(backend, 2, i, 0, got) != 0) {
            fprintf(stderr, "  FAIL %s odd128[%d]: export refused\n", name, i);
            failures++;
            continue;
        }
        shifted_scalar(scalar, (unsigned)(2 * i + 1), (unsigned)odd_shift);
        if (ama_ed25519_scalarmult_public(want, scalar, base_compressed) != AMA_SUCCESS) {
            fprintf(stderr, "  FAIL %s odd128[%d]: reference scalarmult refused\n", name, i);
            failures++;
            continue;
        }
        compared++;
        if (memcmp(got, want, 32) != 0) {
            fprintf(stderr, "  FAIL %s odd128[%d] != %d * 2^%d * B\n", name, i, 2 * i + 1,
                    odd_shift);
            failures++;
        }
    }

    /* Out-of-range indices must be refused, not read past the table. */
    if (ama_ed25519_test_table_entry(backend, 0, tables, 0, got) == 0 ||
        ama_ed25519_test_table_entry(backend, 0, 0, entries, got) == 0 ||
        ama_ed25519_test_table_entry(backend, 1, odd_count, 0, got) == 0 ||
        ama_ed25519_test_table_entry(backend, 2, odd_count, 0, got) == 0 ||
        ama_ed25519_test_table_entry(backend, 3, 0, 0, got) == 0) {
        fprintf(stderr, "  FAIL %s: an out-of-range index was accepted\n", name);
        failures++;
    }

    printf("  %s: %d entries compared, %d failure(s)\n", name, compared, failures);
    if (compared != tables * entries + 2 * odd_count) {
        fprintf(stderr, "  FAIL %s: compared %d of %d entries\n",
                name, compared, tables * entries + 2 * odd_count);
        failures++;
    }
    return failures;
}

int main(void) {
    int failures = 0;
    int present = 0;
    int tables, entries, stride, odd_count, odd_shift;

    printf("Ed25519 static table check (entries vs the variable-base ladder from B)\n");
    failures += check_backend(0, "fe51");
    present += ama_ed25519_test_table_geometry(0, &tables, &entries, &stride, &odd_count,
                                               &odd_shift) == 0;
    failures += check_backend(1, "fe64-mulx");
    present += ama_ed25519_test_table_geometry(1, &tables, &entries, &stride, &odd_count,
                                               &odd_shift) == 0;

    if (present == 0) {
        fprintf(stderr, "FAIL: no backend exposed its tables — nothing was checked\n");
        return 1;
    }
    if (failures != 0) {
        fprintf(stderr, "FAIL: %d table entr%s wrong\n", failures, failures == 1 ? "y is" : "ies are");
        return 1;
    }
    printf("PASS: every static table entry is the multiple of B it claims to be (%d backend%s)\n",
           present, present == 1 ? "" : "s");
    return 0;
}
