/* Copyright (C) 2025-2026 Steel Security Advisors LLC */
/* SPDX-License-Identifier: Apache-2.0 */
/**
 * @file ama_ed25519.c
 * @brief Ed25519 digital signatures (RFC 8032) — the in-house backend.
 * @author Andrew E. A., Steel Security Advisors LLC
 * @date 2026-04-06
 *
 * Twisted Edwards curve -x^2 + y^2 = 1 + d x^2 y^2 over GF(2^255 - 19),
 * d = -121665/121666, base point of order
 * l = 2^252 + 27742317777372353535851937790883648493.
 *
 * STRUCTURE
 *
 * This file owns everything that is independent of the field representation:
 * the RFC 8032 protocol (hashing, clamping, the canonical-encoding rules),
 * the scalar arithmetic mod l, the recoding of scalars into comb and wNAF
 * digits, and the public API.  The group arithmetic — point addition,
 * doubling, the constant-time fixed-base comb, the variable-time wNAF ladders,
 * compression and decompression — lives once in
 * src/c/internal/ama_ed25519_ge.h and is instantiated over two fields:
 *
 *   fe51       radix 2^51, five limbs (src/c/fe51.h).  Instantiated below,
 *              in this translation unit.  Every target compiles it; it is the
 *              only path on AArch64 and on MSVC.
 *   fe64-mulx  radix 2^64, four limbs, the MULX+ADX multiply and square
 *              kernel.  Instantiated in src/c/x86/ama_ed25519_fe64_mulx.c,
 *              compiled per-file with -mbmi2 -madx on x86-64 GCC/Clang, and
 *              selected here at run time when ama_cpuid_has_x25519_mulx()
 *              reports BMI2 and ADX — the same gate X25519 uses.
 *
 * Both instantiations read the same static base-point tables
 * (src/c/internal/ama_ed25519_tables.h, generated by
 * tools/gen_ed25519_tables.py in each radix) and produce byte-identical
 * results; tests/c/test_ed25519_fe51_mulx_equiv.c pins that on every x86-64
 * host that has both.  There is no lazy initialisation anywhere on this path:
 * the tables are `static const`, and no function in this file or in the
 * template writes file-scope state.
 *
 * SECURITY PROPERTIES
 * - Constant-time field arithmetic on every secret-scalar path.
 * - Constant-time fixed-base scalar multiplication: fixed digit count, a
 *   table selection that reads every entry of its row and combines with
 *   masks, sign applied by masked swap and masked negate.  INVARIANT-12.
 * - Secret-derived stack state is scrubbed on every exit (INVARIANT-6).
 * - Scalar clamping and the RFC 8032 canonical-encoding rules for S, R, the
 *   public key's y and the x = 0 sign bit (INVARIANT-26, INVARIANT-38).
 *
 * The variable-time routines (verify, batch verify, the public scalar-mult
 * primitives FROST uses) take PUBLIC scalars only and say so at each site.
 */

#include "../include/ama_cryptography.h"
#include "../include/ama_cpuid.h"
#include "internal/ama_sha2.h"
#include "internal/ama_ed25519_canonical.h"
#include "internal/ama_ed25519_backend.h"
#include "internal/ama_ed25519_halfsize.h"
#include "internal/ama_testing_exports.h"
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include "fe51.h"

#if !defined(AMA_FE51_AVAILABLE)
#error "ama_ed25519.c requires the fe51 field (src/c/fe51.h) on this toolchain"
#endif

/* SHA-512 provided by internal/ama_sha2.h (shared with ama_slhdsa.c); the
 * public AMA_API ama_sha512 lives in src/c/ama_sha512.c. */
#define sha512 ama_sha512_oneshot

/* Stack buffer threshold: messages up to 4KB use stack allocation,
 * larger messages fall back to heap. Covers >99% of real-world use
 * (TLS records, JWT tokens, API payloads, etc.). */
#define ED25519_STACK_THRESHOLD 4096

/* ============================================================================
 * GROUP ARITHMETIC — fe51 instantiation of internal/ama_ed25519_ge.h
 * ============================================================================ */

#define AMA_ED25519_TABLES_FE51
#include "internal/ama_ed25519_tables.h"

#define GE_SUFFIX fe51
#define GE_LINKAGE static
#define GE_FE fe51
#define GE_FE_LIMBS 5
#define GE_FE_0(h) fe51_0(h)
#define GE_FE_1(h) fe51_1(h)
#define GE_FE_COPY(h, f) fe51_copy(h, f)
#define GE_FE_ADD(h, f, g) fe51_add(h, f, g)
#define GE_FE_SUB(h, f, g) fe51_sub(h, f, g)
#define GE_FE_SUB_M(h, f, g) fe51_sub_2p(h, f, g)
#define GE_FE_SUB_S(h, f, g) fe51_sub_8p(h, f, g)
#define GE_FE_NEG(h, f) fe51_neg(h, f)
#define GE_FE_MUL(h, f, g) fe51_mul(h, f, g)
#define GE_FE_SQ(h, f) fe51_sq(h, f)
#define GE_FE_FROMBYTES(h, s) fe51_frombytes(h, s)
#define GE_FE_TOBYTES(s, h) fe51_tobytes(s, h)
#define GE_NIELS ama_ed25519_niels_fe51
#define GE_TABLE_COMB ama_ed25519_base_comb_fe51
#define GE_TABLE_ODD ama_ed25519_base_odd_fe51
#define GE_TABLE_ODD128 ama_ed25519_base_odd128_fe51
#define GE_CONST_D ama_ed25519_const_d_fe51
#define GE_CONST_D2 ama_ed25519_const_d2_fe51
#define GE_CONST_SQRTM1 ama_ed25519_const_sqrtm1_fe51
#if defined(AMA_HAVE_AVX2_IMPL) && (defined(__x86_64__) || defined(_M_X64))
#define GE_NIELS_FOLD_AVX2 ama_ed25519_select15_avx2
#define GE_HAVE_AVX2() ama_has_avx2()
#endif
#include "internal/ama_ed25519_ge.h"

/* ============================================================================
 * BACKEND DISPATCH
 *
 * On x86-64 GCC/Clang builds the MULX+ADX instantiation is linked in and
 * selectable at run time; everywhere else the fe51 instantiation above is
 * the only one and the dispatch macro collapses to a direct call.
 *
 * The default is fe51 on every host, by measurement, not by ISA: with both
 * instantiations alternating in one process on the reference x86-64 host
 * (so both see the same machine state), the MULX path ties fe51 on keygen
 * and sign (ratio 1.00-1.01) and loses on verify and double-scalar-mult
 * (1.10 and 1.13-1.15).  The fused MULX kernel does win the field-multiply
 * microbenchmark (18.4 against 23.1 cycles per multiply in throughput), but
 * the group formulas spend about 1.5 additions or subtractions per
 * multiplication, and on radix 2^64 every one of those carries fully while
 * radix 2^51 leaves them carry-free.  The MULX instantiation stays compiled,
 * byte-identical (tests/c/test_ed25519_fe51_mulx_equiv.c) and reachable
 * through the override, so the choice can be re-measured on any host with
 * one call; the override mirrors ama_x25519_set_mulx_override(): a
 * benchmark/test knob, single-threaded by contract, never a production
 * policy.
 * ============================================================================ */

#if defined(AMA_HAVE_ED25519_FE64_MULX_IMPL)
static int ama_ed25519_mulx_override = -1;

static int ed25519_use_mulx(void) {
    int mode = ama_ed25519_mulx_override;
    return mode == 1 && ama_cpuid_has_x25519_mulx();
}

AMA_API void ama_ed25519_set_mulx_override(int mode) {
    ama_ed25519_mulx_override = (mode < 0) ? -1 : (mode != 0);
}

#define ED_DISPATCH(fn, ...) \
    (ed25519_use_mulx() ? fn##_mulx(__VA_ARGS__) : fn##_fe51(__VA_ARGS__))
#else
AMA_API void ama_ed25519_set_mulx_override(int mode) {
    (void)mode;
}

#define ED_DISPATCH(fn, ...) fn##_fe51(__VA_ARGS__)
#endif

/* Which group-arithmetic instantiation the next call will run on. */
AMA_API const char *ama_ed25519_active_backend(void) {
#if defined(AMA_HAVE_ED25519_FE64_MULX_IMPL)
    return ed25519_use_mulx() ? "fe64-mulx" : "fe51";
#else
    return "fe51";
#endif
}

/* ============================================================================
 * SCALAR ARITHMETIC: mod l
 * ============================================================================ */

/* Helper: load 3/4 bytes little-endian (used by scalar arithmetic) */
static int64_t load_3(const uint8_t *in) {
    return (int64_t)in[0] | ((int64_t)in[1] << 8) | ((int64_t)in[2] << 16);
}
static int64_t load_4(const uint8_t *in) {
    return (int64_t)in[0] | ((int64_t)in[1] << 8) | ((int64_t)in[2] << 16) | ((int64_t)in[3] << 24);
}

/*
 * Reduce a 64-byte (512-bit) scalar mod L.
 * L = 2^252 + 27742317777372353535851937790883648493
 * Based on the SUPERCOP ref10 sc_reduce implementation.
 * Input: 64-byte SHA-512 hash. Output: 32-byte reduced scalar (in-place).
 */
static void sc25519_reduce(uint8_t *s) {
    /*
     * Load all 64 bytes into 24 limbs of 21 bits each.
     * Uses load_3/load_4 helpers with ref10 byte offsets.
     * Each limb starts at bit position i*21, which falls at byte floor(i*21/8)
     * with bit offset (i*21) mod 8.
     */
    int64_t s0 = 2097151 & load_3(s + 0);
    int64_t s1 = 2097151 & (load_4(s + 2) >> 5);
    int64_t s2 = 2097151 & (load_3(s + 5) >> 2);
    int64_t s3 = 2097151 & (load_4(s + 7) >> 7);
    int64_t s4 = 2097151 & (load_4(s + 10) >> 4);
    int64_t s5 = 2097151 & (load_3(s + 13) >> 1);
    int64_t s6 = 2097151 & (load_4(s + 15) >> 6);
    int64_t s7 = 2097151 & (load_4(s + 18) >> 3);
    int64_t s8 = 2097151 & load_3(s + 21);
    int64_t s9 = 2097151 & (load_4(s + 23) >> 5);
    int64_t s10 = 2097151 & (load_3(s + 26) >> 2);
    int64_t s11 = 2097151 & (load_4(s + 28) >> 7);
    int64_t s12 = 2097151 & (load_4(s + 31) >> 4);
    int64_t s13 = 2097151 & (load_3(s + 34) >> 1);
    int64_t s14 = 2097151 & (load_4(s + 36) >> 6);
    int64_t s15 = 2097151 & (load_4(s + 39) >> 3);
    int64_t s16 = 2097151 & load_3(s + 42);
    int64_t s17 = 2097151 & (load_4(s + 44) >> 5);
    int64_t s18 = 2097151 & (load_3(s + 47) >> 2);
    int64_t s19 = 2097151 & (load_4(s + 49) >> 7);
    int64_t s20 = 2097151 & (load_4(s + 52) >> 4);
    int64_t s21 = 2097151 & (load_3(s + 55) >> 1);
    int64_t s22 = 2097151 & (load_4(s + 57) >> 6);
    int64_t s23 = (load_4(s + 60) >> 3);

    int64_t carry;

    /* First pass: reduce s23..s18 into s11..s16 range */
    s11 += s23 * 666643; s12 += s23 * 470296; s13 += s23 * 654183;
    s14 -= s23 * 997805; s15 += s23 * 136657; s16 -= s23 * 683901;
    ama_secure_memzero(&s23, sizeof(s23));

    s10 += s22 * 666643; s11 += s22 * 470296; s12 += s22 * 654183;
    s13 -= s22 * 997805; s14 += s22 * 136657; s15 -= s22 * 683901;
    ama_secure_memzero(&s22, sizeof(s22));

    s9 += s21 * 666643; s10 += s21 * 470296; s11 += s21 * 654183;
    s12 -= s21 * 997805; s13 += s21 * 136657; s14 -= s21 * 683901;
    ama_secure_memzero(&s21, sizeof(s21));

    s8 += s20 * 666643; s9 += s20 * 470296; s10 += s20 * 654183;
    s11 -= s20 * 997805; s12 += s20 * 136657; s13 -= s20 * 683901;
    ama_secure_memzero(&s20, sizeof(s20));

    s7 += s19 * 666643; s8 += s19 * 470296; s9 += s19 * 654183;
    s10 -= s19 * 997805; s11 += s19 * 136657; s12 -= s19 * 683901;
    ama_secure_memzero(&s19, sizeof(s19));

    s6 += s18 * 666643; s7 += s18 * 470296; s8 += s18 * 654183;
    s9 -= s18 * 997805; s10 += s18 * 136657; s11 -= s18 * 683901;
    ama_secure_memzero(&s18, sizeof(s18));

    /* Carry propagation (first round)
     * Use multiplication instead of left-shift to avoid UB on negative carry
     * (C99/C11: left-shift of negative signed integer is undefined behavior) */
    carry = (s6 + ((int64_t)1 << 20)) >> 21; s7 += carry; s6 -= carry * ((int64_t)1 << 21);
    carry = (s8 + ((int64_t)1 << 20)) >> 21; s9 += carry; s8 -= carry * ((int64_t)1 << 21);
    carry = (s10 + ((int64_t)1 << 20)) >> 21; s11 += carry; s10 -= carry * ((int64_t)1 << 21);
    carry = (s12 + ((int64_t)1 << 20)) >> 21; s13 += carry; s12 -= carry * ((int64_t)1 << 21);
    carry = (s14 + ((int64_t)1 << 20)) >> 21; s15 += carry; s14 -= carry * ((int64_t)1 << 21);
    carry = (s16 + ((int64_t)1 << 20)) >> 21; s17 += carry; s16 -= carry * ((int64_t)1 << 21);

    carry = (s7 + ((int64_t)1 << 20)) >> 21; s8 += carry; s7 -= carry * ((int64_t)1 << 21);
    carry = (s9 + ((int64_t)1 << 20)) >> 21; s10 += carry; s9 -= carry * ((int64_t)1 << 21);
    carry = (s11 + ((int64_t)1 << 20)) >> 21; s12 += carry; s11 -= carry * ((int64_t)1 << 21);
    carry = (s13 + ((int64_t)1 << 20)) >> 21; s14 += carry; s13 -= carry * ((int64_t)1 << 21);
    carry = (s15 + ((int64_t)1 << 20)) >> 21; s16 += carry; s15 -= carry * ((int64_t)1 << 21);

    /* Second pass: reduce s17..s12 into s5..s10 range */
    s5 += s17 * 666643; s6 += s17 * 470296; s7 += s17 * 654183;
    s8 -= s17 * 997805; s9 += s17 * 136657; s10 -= s17 * 683901;
    ama_secure_memzero(&s17, sizeof(s17));

    s4 += s16 * 666643; s5 += s16 * 470296; s6 += s16 * 654183;
    s7 -= s16 * 997805; s8 += s16 * 136657; s9 -= s16 * 683901;
    ama_secure_memzero(&s16, sizeof(s16));

    s3 += s15 * 666643; s4 += s15 * 470296; s5 += s15 * 654183;
    s6 -= s15 * 997805; s7 += s15 * 136657; s8 -= s15 * 683901;
    ama_secure_memzero(&s15, sizeof(s15));

    s2 += s14 * 666643; s3 += s14 * 470296; s4 += s14 * 654183;
    s5 -= s14 * 997805; s6 += s14 * 136657; s7 -= s14 * 683901;
    ama_secure_memzero(&s14, sizeof(s14));

    s1 += s13 * 666643; s2 += s13 * 470296; s3 += s13 * 654183;
    s4 -= s13 * 997805; s5 += s13 * 136657; s6 -= s13 * 683901;
    ama_secure_memzero(&s13, sizeof(s13));

    s0 += s12 * 666643; s1 += s12 * 470296; s2 += s12 * 654183;
    s3 -= s12 * 997805; s4 += s12 * 136657; s5 -= s12 * 683901;
    ama_secure_memzero(&s12, sizeof(s12));

    /* Carry propagation — interleaved evens then odds (ref10 pattern) */
    carry = (s0 + ((int64_t)1 << 20)) >> 21; s1 += carry; s0 -= carry * ((int64_t)1 << 21);
    carry = (s2 + ((int64_t)1 << 20)) >> 21; s3 += carry; s2 -= carry * ((int64_t)1 << 21);
    carry = (s4 + ((int64_t)1 << 20)) >> 21; s5 += carry; s4 -= carry * ((int64_t)1 << 21);
    carry = (s6 + ((int64_t)1 << 20)) >> 21; s7 += carry; s6 -= carry * ((int64_t)1 << 21);
    carry = (s8 + ((int64_t)1 << 20)) >> 21; s9 += carry; s8 -= carry * ((int64_t)1 << 21);
    carry = (s10 + ((int64_t)1 << 20)) >> 21; s11 += carry; s10 -= carry * ((int64_t)1 << 21);

    carry = (s1 + ((int64_t)1 << 20)) >> 21; s2 += carry; s1 -= carry * ((int64_t)1 << 21);
    carry = (s3 + ((int64_t)1 << 20)) >> 21; s4 += carry; s3 -= carry * ((int64_t)1 << 21);
    carry = (s5 + ((int64_t)1 << 20)) >> 21; s6 += carry; s5 -= carry * ((int64_t)1 << 21);
    carry = (s7 + ((int64_t)1 << 20)) >> 21; s8 += carry; s7 -= carry * ((int64_t)1 << 21);
    carry = (s9 + ((int64_t)1 << 20)) >> 21; s10 += carry; s9 -= carry * ((int64_t)1 << 21);
    carry = (s11 + ((int64_t)1 << 20)) >> 21; s12 += carry; s11 -= carry * ((int64_t)1 << 21);

    /* Reduce s12 overflow via L coefficients */
    s0 += s12 * 666643; s1 += s12 * 470296; s2 += s12 * 654183;
    s3 -= s12 * 997805; s4 += s12 * 136657; s5 -= s12 * 683901;
    ama_secure_memzero(&s12, sizeof(s12));

    /* Sequential carry using floor division (>> 21) */
    carry = s0 >> 21; s1 += carry; s0 -= carry * ((int64_t)1 << 21);
    carry = s1 >> 21; s2 += carry; s1 -= carry * ((int64_t)1 << 21);
    carry = s2 >> 21; s3 += carry; s2 -= carry * ((int64_t)1 << 21);
    carry = s3 >> 21; s4 += carry; s3 -= carry * ((int64_t)1 << 21);
    carry = s4 >> 21; s5 += carry; s4 -= carry * ((int64_t)1 << 21);
    carry = s5 >> 21; s6 += carry; s5 -= carry * ((int64_t)1 << 21);
    carry = s6 >> 21; s7 += carry; s6 -= carry * ((int64_t)1 << 21);
    carry = s7 >> 21; s8 += carry; s7 -= carry * ((int64_t)1 << 21);
    carry = s8 >> 21; s9 += carry; s8 -= carry * ((int64_t)1 << 21);
    carry = s9 >> 21; s10 += carry; s9 -= carry * ((int64_t)1 << 21);
    carry = s10 >> 21; s11 += carry; s10 -= carry * ((int64_t)1 << 21);
    carry = s11 >> 21; s12 += carry; s11 -= carry * ((int64_t)1 << 21);

    /* Second s12 wrap-around */
    s0 += s12 * 666643; s1 += s12 * 470296; s2 += s12 * 654183;
    s3 -= s12 * 997805; s4 += s12 * 136657; s5 -= s12 * 683901;
    ama_secure_memzero(&s12, sizeof(s12));

    /* Final sequential carry */
    carry = s0 >> 21; s1 += carry; s0 -= carry * ((int64_t)1 << 21);
    carry = s1 >> 21; s2 += carry; s1 -= carry * ((int64_t)1 << 21);
    carry = s2 >> 21; s3 += carry; s2 -= carry * ((int64_t)1 << 21);
    carry = s3 >> 21; s4 += carry; s3 -= carry * ((int64_t)1 << 21);
    carry = s4 >> 21; s5 += carry; s4 -= carry * ((int64_t)1 << 21);
    carry = s5 >> 21; s6 += carry; s5 -= carry * ((int64_t)1 << 21);
    carry = s6 >> 21; s7 += carry; s6 -= carry * ((int64_t)1 << 21);
    carry = s7 >> 21; s8 += carry; s7 -= carry * ((int64_t)1 << 21);
    carry = s8 >> 21; s9 += carry; s8 -= carry * ((int64_t)1 << 21);
    carry = s9 >> 21; s10 += carry; s9 -= carry * ((int64_t)1 << 21);
    carry = s10 >> 21; s11 += carry; s10 -= carry * ((int64_t)1 << 21);

    /* Pack 12 limbs into 32 bytes */
    s[0] = (uint8_t)(s0 >> 0);
    s[1] = (uint8_t)(s0 >> 8);
    s[2] = (uint8_t)((s0 >> 16) | (s1 << 5));
    s[3] = (uint8_t)(s1 >> 3);
    s[4] = (uint8_t)(s1 >> 11);
    s[5] = (uint8_t)((s1 >> 19) | (s2 << 2));
    s[6] = (uint8_t)(s2 >> 6);
    s[7] = (uint8_t)((s2 >> 14) | (s3 << 7));
    s[8] = (uint8_t)(s3 >> 1);
    s[9] = (uint8_t)(s3 >> 9);
    s[10] = (uint8_t)((s3 >> 17) | (s4 << 4));
    s[11] = (uint8_t)(s4 >> 4);
    s[12] = (uint8_t)(s4 >> 12);
    s[13] = (uint8_t)((s4 >> 20) | (s5 << 1));
    s[14] = (uint8_t)(s5 >> 7);
    s[15] = (uint8_t)((s5 >> 15) | (s6 << 6));
    s[16] = (uint8_t)(s6 >> 2);
    s[17] = (uint8_t)(s6 >> 10);
    s[18] = (uint8_t)((s6 >> 18) | (s7 << 3));
    s[19] = (uint8_t)(s7 >> 5);
    s[20] = (uint8_t)(s7 >> 13);
    s[21] = (uint8_t)(s8 >> 0);
    s[22] = (uint8_t)(s8 >> 8);
    s[23] = (uint8_t)((s8 >> 16) | (s9 << 5));
    s[24] = (uint8_t)(s9 >> 3);
    s[25] = (uint8_t)(s9 >> 11);
    s[26] = (uint8_t)((s9 >> 19) | (s10 << 2));
    s[27] = (uint8_t)(s10 >> 6);
    s[28] = (uint8_t)((s10 >> 14) | (s11 << 7));
    s[29] = (uint8_t)(s11 >> 1);
    s[30] = (uint8_t)(s11 >> 9);
    s[31] = (uint8_t)(s11 >> 17);
}

/* Compute s = a + b*c mod L */
static void sc25519_muladd(uint8_t *s, const uint8_t *a, const uint8_t *b, const uint8_t *c) {
    /* Load 32-byte inputs into 12 limbs of 21 bits each using ref10 byte offsets */
    int64_t a0 = 2097151 & load_3(a + 0);
    int64_t a1 = 2097151 & (load_4(a + 2) >> 5);
    int64_t a2 = 2097151 & (load_3(a + 5) >> 2);
    int64_t a3 = 2097151 & (load_4(a + 7) >> 7);
    int64_t a4 = 2097151 & (load_4(a + 10) >> 4);
    int64_t a5 = 2097151 & (load_3(a + 13) >> 1);
    int64_t a6 = 2097151 & (load_4(a + 15) >> 6);
    int64_t a7 = 2097151 & (load_4(a + 18) >> 3);
    int64_t a8 = 2097151 & load_3(a + 21);
    int64_t a9 = 2097151 & (load_4(a + 23) >> 5);
    int64_t a10 = 2097151 & (load_3(a + 26) >> 2);
    int64_t a11 = (load_4(a + 28) >> 7);

    int64_t b0 = 2097151 & load_3(b + 0);
    int64_t b1 = 2097151 & (load_4(b + 2) >> 5);
    int64_t b2 = 2097151 & (load_3(b + 5) >> 2);
    int64_t b3 = 2097151 & (load_4(b + 7) >> 7);
    int64_t b4 = 2097151 & (load_4(b + 10) >> 4);
    int64_t b5 = 2097151 & (load_3(b + 13) >> 1);
    int64_t b6 = 2097151 & (load_4(b + 15) >> 6);
    int64_t b7 = 2097151 & (load_4(b + 18) >> 3);
    int64_t b8 = 2097151 & load_3(b + 21);
    int64_t b9 = 2097151 & (load_4(b + 23) >> 5);
    int64_t b10 = 2097151 & (load_3(b + 26) >> 2);
    int64_t b11 = (load_4(b + 28) >> 7);

    int64_t c0 = 2097151 & load_3(c + 0);
    int64_t c1 = 2097151 & (load_4(c + 2) >> 5);
    int64_t c2 = 2097151 & (load_3(c + 5) >> 2);
    int64_t c3 = 2097151 & (load_4(c + 7) >> 7);
    int64_t c4 = 2097151 & (load_4(c + 10) >> 4);
    int64_t c5 = 2097151 & (load_3(c + 13) >> 1);
    int64_t c6 = 2097151 & (load_4(c + 15) >> 6);
    int64_t c7 = 2097151 & (load_4(c + 18) >> 3);
    int64_t c8 = 2097151 & load_3(c + 21);
    int64_t c9 = 2097151 & (load_4(c + 23) >> 5);
    int64_t c10 = 2097151 & (load_3(c + 26) >> 2);
    int64_t c11 = (load_4(c + 28) >> 7);

    /* s = a + b*c */
    int64_t s0 = a0 + b0*c0;
    int64_t s1 = a1 + b0*c1 + b1*c0;
    int64_t s2 = a2 + b0*c2 + b1*c1 + b2*c0;
    int64_t s3 = a3 + b0*c3 + b1*c2 + b2*c1 + b3*c0;
    int64_t s4 = a4 + b0*c4 + b1*c3 + b2*c2 + b3*c1 + b4*c0;
    int64_t s5 = a5 + b0*c5 + b1*c4 + b2*c3 + b3*c2 + b4*c1 + b5*c0;
    int64_t s6 = a6 + b0*c6 + b1*c5 + b2*c4 + b3*c3 + b4*c2 + b5*c1 + b6*c0;
    int64_t s7 = a7 + b0*c7 + b1*c6 + b2*c5 + b3*c4 + b4*c3 + b5*c2 + b6*c1 + b7*c0;
    int64_t s8 = a8 + b0*c8 + b1*c7 + b2*c6 + b3*c5 + b4*c4 + b5*c3 + b6*c2 + b7*c1 + b8*c0;
    int64_t s9 = a9 + b0*c9 + b1*c8 + b2*c7 + b3*c6 + b4*c5 + b5*c4 + b6*c3 + b7*c2 + b8*c1 + b9*c0;
    int64_t s10 = a10 + b0*c10 + b1*c9 + b2*c8 + b3*c7 + b4*c6 + b5*c5 + b6*c4 + b7*c3 + b8*c2 + b9*c1 + b10*c0;
    int64_t s11 = a11 + b0*c11 + b1*c10 + b2*c9 + b3*c8 + b4*c7 + b5*c6 + b6*c5 + b7*c4 + b8*c3 + b9*c2 + b10*c1 + b11*c0;
    int64_t s12 = b1*c11 + b2*c10 + b3*c9 + b4*c8 + b5*c7 + b6*c6 + b7*c5 + b8*c4 + b9*c3 + b10*c2 + b11*c1;
    int64_t s13 = b2*c11 + b3*c10 + b4*c9 + b5*c8 + b6*c7 + b7*c6 + b8*c5 + b9*c4 + b10*c3 + b11*c2;
    int64_t s14 = b3*c11 + b4*c10 + b5*c9 + b6*c8 + b7*c7 + b8*c6 + b9*c5 + b10*c4 + b11*c3;
    int64_t s15 = b4*c11 + b5*c10 + b6*c9 + b7*c8 + b8*c7 + b9*c6 + b10*c5 + b11*c4;
    int64_t s16 = b5*c11 + b6*c10 + b7*c9 + b8*c8 + b9*c7 + b10*c6 + b11*c5;
    int64_t s17 = b6*c11 + b7*c10 + b8*c9 + b9*c8 + b10*c7 + b11*c6;
    int64_t s18 = b7*c11 + b8*c10 + b9*c9 + b10*c8 + b11*c7;
    int64_t s19 = b8*c11 + b9*c10 + b10*c9 + b11*c8;
    int64_t s20 = b9*c11 + b10*c10 + b11*c9;
    int64_t s21 = b10*c11 + b11*c10;
    int64_t s22 = b11*c11;
    int64_t s23 = 0;

    int64_t carry;

    /* Reduce mod L */
    carry = (s0 + ((int64_t)1 << 20)) >> 21; s1 += carry; s0 -= carry * ((int64_t)1 << 21);
    carry = (s2 + ((int64_t)1 << 20)) >> 21; s3 += carry; s2 -= carry * ((int64_t)1 << 21);
    carry = (s4 + ((int64_t)1 << 20)) >> 21; s5 += carry; s4 -= carry * ((int64_t)1 << 21);
    carry = (s6 + ((int64_t)1 << 20)) >> 21; s7 += carry; s6 -= carry * ((int64_t)1 << 21);
    carry = (s8 + ((int64_t)1 << 20)) >> 21; s9 += carry; s8 -= carry * ((int64_t)1 << 21);
    carry = (s10 + ((int64_t)1 << 20)) >> 21; s11 += carry; s10 -= carry * ((int64_t)1 << 21);
    carry = (s12 + ((int64_t)1 << 20)) >> 21; s13 += carry; s12 -= carry * ((int64_t)1 << 21);
    carry = (s14 + ((int64_t)1 << 20)) >> 21; s15 += carry; s14 -= carry * ((int64_t)1 << 21);
    carry = (s16 + ((int64_t)1 << 20)) >> 21; s17 += carry; s16 -= carry * ((int64_t)1 << 21);
    carry = (s18 + ((int64_t)1 << 20)) >> 21; s19 += carry; s18 -= carry * ((int64_t)1 << 21);
    carry = (s20 + ((int64_t)1 << 20)) >> 21; s21 += carry; s20 -= carry * ((int64_t)1 << 21);
    carry = (s22 + ((int64_t)1 << 20)) >> 21; s23 += carry; s22 -= carry * ((int64_t)1 << 21);

    carry = (s1 + ((int64_t)1 << 20)) >> 21; s2 += carry; s1 -= carry * ((int64_t)1 << 21);
    carry = (s3 + ((int64_t)1 << 20)) >> 21; s4 += carry; s3 -= carry * ((int64_t)1 << 21);
    carry = (s5 + ((int64_t)1 << 20)) >> 21; s6 += carry; s5 -= carry * ((int64_t)1 << 21);
    carry = (s7 + ((int64_t)1 << 20)) >> 21; s8 += carry; s7 -= carry * ((int64_t)1 << 21);
    carry = (s9 + ((int64_t)1 << 20)) >> 21; s10 += carry; s9 -= carry * ((int64_t)1 << 21);
    carry = (s11 + ((int64_t)1 << 20)) >> 21; s12 += carry; s11 -= carry * ((int64_t)1 << 21);
    carry = (s13 + ((int64_t)1 << 20)) >> 21; s14 += carry; s13 -= carry * ((int64_t)1 << 21);
    carry = (s15 + ((int64_t)1 << 20)) >> 21; s16 += carry; s15 -= carry * ((int64_t)1 << 21);
    carry = (s17 + ((int64_t)1 << 20)) >> 21; s18 += carry; s17 -= carry * ((int64_t)1 << 21);
    carry = (s19 + ((int64_t)1 << 20)) >> 21; s20 += carry; s19 -= carry * ((int64_t)1 << 21);
    carry = (s21 + ((int64_t)1 << 20)) >> 21; s22 += carry; s21 -= carry * ((int64_t)1 << 21);

    /* Reduce high limbs */
    s11 += s23 * 666643; s12 += s23 * 470296; s13 += s23 * 654183;
    s14 -= s23 * 997805; s15 += s23 * 136657; s16 -= s23 * 683901;
    ama_secure_memzero(&s23, sizeof(s23));

    s10 += s22 * 666643; s11 += s22 * 470296; s12 += s22 * 654183;
    s13 -= s22 * 997805; s14 += s22 * 136657; s15 -= s22 * 683901;
    ama_secure_memzero(&s22, sizeof(s22));

    s9 += s21 * 666643; s10 += s21 * 470296; s11 += s21 * 654183;
    s12 -= s21 * 997805; s13 += s21 * 136657; s14 -= s21 * 683901;
    ama_secure_memzero(&s21, sizeof(s21));

    s8 += s20 * 666643; s9 += s20 * 470296; s10 += s20 * 654183;
    s11 -= s20 * 997805; s12 += s20 * 136657; s13 -= s20 * 683901;
    ama_secure_memzero(&s20, sizeof(s20));

    s7 += s19 * 666643; s8 += s19 * 470296; s9 += s19 * 654183;
    s10 -= s19 * 997805; s11 += s19 * 136657; s12 -= s19 * 683901;
    ama_secure_memzero(&s19, sizeof(s19));

    s6 += s18 * 666643; s7 += s18 * 470296; s8 += s18 * 654183;
    s9 -= s18 * 997805; s10 += s18 * 136657; s11 -= s18 * 683901;
    ama_secure_memzero(&s18, sizeof(s18));

    carry = (s6 + ((int64_t)1 << 20)) >> 21; s7 += carry; s6 -= carry * ((int64_t)1 << 21);
    carry = (s8 + ((int64_t)1 << 20)) >> 21; s9 += carry; s8 -= carry * ((int64_t)1 << 21);
    carry = (s10 + ((int64_t)1 << 20)) >> 21; s11 += carry; s10 -= carry * ((int64_t)1 << 21);
    carry = (s12 + ((int64_t)1 << 20)) >> 21; s13 += carry; s12 -= carry * ((int64_t)1 << 21);
    carry = (s14 + ((int64_t)1 << 20)) >> 21; s15 += carry; s14 -= carry * ((int64_t)1 << 21);
    carry = (s16 + ((int64_t)1 << 20)) >> 21; s17 += carry; s16 -= carry * ((int64_t)1 << 21);

    carry = (s7 + ((int64_t)1 << 20)) >> 21; s8 += carry; s7 -= carry * ((int64_t)1 << 21);
    carry = (s9 + ((int64_t)1 << 20)) >> 21; s10 += carry; s9 -= carry * ((int64_t)1 << 21);
    carry = (s11 + ((int64_t)1 << 20)) >> 21; s12 += carry; s11 -= carry * ((int64_t)1 << 21);
    carry = (s13 + ((int64_t)1 << 20)) >> 21; s14 += carry; s13 -= carry * ((int64_t)1 << 21);
    carry = (s15 + ((int64_t)1 << 20)) >> 21; s16 += carry; s15 -= carry * ((int64_t)1 << 21);

    s5 += s17 * 666643; s6 += s17 * 470296; s7 += s17 * 654183;
    s8 -= s17 * 997805; s9 += s17 * 136657; s10 -= s17 * 683901;
    ama_secure_memzero(&s17, sizeof(s17));

    s4 += s16 * 666643; s5 += s16 * 470296; s6 += s16 * 654183;
    s7 -= s16 * 997805; s8 += s16 * 136657; s9 -= s16 * 683901;
    ama_secure_memzero(&s16, sizeof(s16));

    s3 += s15 * 666643; s4 += s15 * 470296; s5 += s15 * 654183;
    s6 -= s15 * 997805; s7 += s15 * 136657; s8 -= s15 * 683901;
    ama_secure_memzero(&s15, sizeof(s15));

    s2 += s14 * 666643; s3 += s14 * 470296; s4 += s14 * 654183;
    s5 -= s14 * 997805; s6 += s14 * 136657; s7 -= s14 * 683901;
    ama_secure_memzero(&s14, sizeof(s14));

    s1 += s13 * 666643; s2 += s13 * 470296; s3 += s13 * 654183;
    s4 -= s13 * 997805; s5 += s13 * 136657; s6 -= s13 * 683901;
    ama_secure_memzero(&s13, sizeof(s13));

    s0 += s12 * 666643; s1 += s12 * 470296; s2 += s12 * 654183;
    s3 -= s12 * 997805; s4 += s12 * 136657; s5 -= s12 * 683901;
    ama_secure_memzero(&s12, sizeof(s12));

    /* Carry propagation — interleaved evens then odds (ref10 pattern) */
    carry = (s0 + ((int64_t)1 << 20)) >> 21; s1 += carry; s0 -= carry * ((int64_t)1 << 21);
    carry = (s2 + ((int64_t)1 << 20)) >> 21; s3 += carry; s2 -= carry * ((int64_t)1 << 21);
    carry = (s4 + ((int64_t)1 << 20)) >> 21; s5 += carry; s4 -= carry * ((int64_t)1 << 21);
    carry = (s6 + ((int64_t)1 << 20)) >> 21; s7 += carry; s6 -= carry * ((int64_t)1 << 21);
    carry = (s8 + ((int64_t)1 << 20)) >> 21; s9 += carry; s8 -= carry * ((int64_t)1 << 21);
    carry = (s10 + ((int64_t)1 << 20)) >> 21; s11 += carry; s10 -= carry * ((int64_t)1 << 21);

    carry = (s1 + ((int64_t)1 << 20)) >> 21; s2 += carry; s1 -= carry * ((int64_t)1 << 21);
    carry = (s3 + ((int64_t)1 << 20)) >> 21; s4 += carry; s3 -= carry * ((int64_t)1 << 21);
    carry = (s5 + ((int64_t)1 << 20)) >> 21; s6 += carry; s5 -= carry * ((int64_t)1 << 21);
    carry = (s7 + ((int64_t)1 << 20)) >> 21; s8 += carry; s7 -= carry * ((int64_t)1 << 21);
    carry = (s9 + ((int64_t)1 << 20)) >> 21; s10 += carry; s9 -= carry * ((int64_t)1 << 21);
    carry = (s11 + ((int64_t)1 << 20)) >> 21; s12 += carry; s11 -= carry * ((int64_t)1 << 21);

    /* Reduce s12 overflow via L coefficients */
    s0 += s12 * 666643; s1 += s12 * 470296; s2 += s12 * 654183;
    s3 -= s12 * 997805; s4 += s12 * 136657; s5 -= s12 * 683901;
    ama_secure_memzero(&s12, sizeof(s12));

    /* Sequential carry using floor division (>> 21) */
    carry = s0 >> 21; s1 += carry; s0 -= carry * ((int64_t)1 << 21);
    carry = s1 >> 21; s2 += carry; s1 -= carry * ((int64_t)1 << 21);
    carry = s2 >> 21; s3 += carry; s2 -= carry * ((int64_t)1 << 21);
    carry = s3 >> 21; s4 += carry; s3 -= carry * ((int64_t)1 << 21);
    carry = s4 >> 21; s5 += carry; s4 -= carry * ((int64_t)1 << 21);
    carry = s5 >> 21; s6 += carry; s5 -= carry * ((int64_t)1 << 21);
    carry = s6 >> 21; s7 += carry; s6 -= carry * ((int64_t)1 << 21);
    carry = s7 >> 21; s8 += carry; s7 -= carry * ((int64_t)1 << 21);
    carry = s8 >> 21; s9 += carry; s8 -= carry * ((int64_t)1 << 21);
    carry = s9 >> 21; s10 += carry; s9 -= carry * ((int64_t)1 << 21);
    carry = s10 >> 21; s11 += carry; s10 -= carry * ((int64_t)1 << 21);
    carry = s11 >> 21; s12 += carry; s11 -= carry * ((int64_t)1 << 21);

    /* Second s12 wrap-around */
    s0 += s12 * 666643; s1 += s12 * 470296; s2 += s12 * 654183;
    s3 -= s12 * 997805; s4 += s12 * 136657; s5 -= s12 * 683901;
    ama_secure_memzero(&s12, sizeof(s12));

    /* Final sequential carry */
    carry = s0 >> 21; s1 += carry; s0 -= carry * ((int64_t)1 << 21);
    carry = s1 >> 21; s2 += carry; s1 -= carry * ((int64_t)1 << 21);
    carry = s2 >> 21; s3 += carry; s2 -= carry * ((int64_t)1 << 21);
    carry = s3 >> 21; s4 += carry; s3 -= carry * ((int64_t)1 << 21);
    carry = s4 >> 21; s5 += carry; s4 -= carry * ((int64_t)1 << 21);
    carry = s5 >> 21; s6 += carry; s5 -= carry * ((int64_t)1 << 21);
    carry = s6 >> 21; s7 += carry; s6 -= carry * ((int64_t)1 << 21);
    carry = s7 >> 21; s8 += carry; s7 -= carry * ((int64_t)1 << 21);
    carry = s8 >> 21; s9 += carry; s8 -= carry * ((int64_t)1 << 21);
    carry = s9 >> 21; s10 += carry; s9 -= carry * ((int64_t)1 << 21);
    carry = s10 >> 21; s11 += carry; s10 -= carry * ((int64_t)1 << 21);

    /* Pack 12 limbs into 32 bytes */
    s[0] = (uint8_t)(s0 >> 0);
    s[1] = (uint8_t)(s0 >> 8);
    s[2] = (uint8_t)((s0 >> 16) | (s1 << 5));
    s[3] = (uint8_t)(s1 >> 3);
    s[4] = (uint8_t)(s1 >> 11);
    s[5] = (uint8_t)((s1 >> 19) | (s2 << 2));
    s[6] = (uint8_t)(s2 >> 6);
    s[7] = (uint8_t)((s2 >> 14) | (s3 << 7));
    s[8] = (uint8_t)(s3 >> 1);
    s[9] = (uint8_t)(s3 >> 9);
    s[10] = (uint8_t)((s3 >> 17) | (s4 << 4));
    s[11] = (uint8_t)(s4 >> 4);
    s[12] = (uint8_t)(s4 >> 12);
    s[13] = (uint8_t)((s4 >> 20) | (s5 << 1));
    s[14] = (uint8_t)(s5 >> 7);
    s[15] = (uint8_t)((s5 >> 15) | (s6 << 6));
    s[16] = (uint8_t)(s6 >> 2);
    s[17] = (uint8_t)(s6 >> 10);
    s[18] = (uint8_t)((s6 >> 18) | (s7 << 3));
    s[19] = (uint8_t)(s7 >> 5);
    s[20] = (uint8_t)(s7 >> 13);
    s[21] = (uint8_t)(s8 >> 0);
    s[22] = (uint8_t)(s8 >> 8);
    s[23] = (uint8_t)((s8 >> 16) | (s9 << 5));
    s[24] = (uint8_t)(s9 >> 3);
    s[25] = (uint8_t)(s9 >> 11);
    s[26] = (uint8_t)((s9 >> 19) | (s10 << 2));
    s[27] = (uint8_t)(s10 >> 6);
    s[28] = (uint8_t)((s10 >> 14) | (s11 << 7));
    s[29] = (uint8_t)(s11 >> 1);
    s[30] = (uint8_t)(s11 >> 9);
    s[31] = (uint8_t)(s11 >> 17);
}

/* ============================================================================
 * SCALAR RECODING
 * ============================================================================ */

/* s mod l, for a 32-byte little-endian s in [0, 2^256): zero-extend to the
 * 64-byte input sc25519_reduce expects and reduce in a local buffer.  Every
 * scalar-multiplication entry point canonicalises through here, so the group
 * operation is a function of (s mod l) — which is what the public contract
 * promises ([s]P == [s mod l]P, and the linearity identity
 * point_from_scalar(a) + point_from_scalar(b) == point_from_scalar(a + b)
 * for every 32-byte input, reduced or not).  The scrub is INVARIANT-6; the
 * buffer holds the secret on the comb path. */
static void sc25519_reduce32(uint8_t out[32], const uint8_t s[32]) {
    uint8_t wide[64];
    memcpy(wide, s, 32);
    ama_secure_memzero(wide + 32, 32);
    sc25519_reduce(wide);
    memcpy(out, wide, 32);
    ama_secure_memzero(wide, sizeof wide);
}

/* Signed W-bit comb digits of a reduced scalar (s < l < 2^253).
 *
 * Unsigned W-bit digits are extracted first — digit i is bits [Wi, Wi+W) —
 * then rebalanced by carry so every digit lies in [-2^(W-1), 2^(W-1) - 1],
 * which lets the comb table hold only the positive multiples 1..2^(W-1) and
 * apply the sign by negation.  The carry out of the last rebalanced digit is
 * added to the top digit, which can therefore reach 2^(W-1) exactly; the
 * selection routine accepts that magnitude.  Because s < 2^253 the top
 * digit's own bits are already small, so no carry escapes the digit count.
 *
 * CONSTANT TIME: byte indices and shifts depend on i only; the carry is
 * computed arithmetically.  The digit array is the secret's expansion and is
 * scrubbed by the caller (INVARIANT-6). */
static void ed25519_comb_digits(int8_t e[AMA_ED25519_COMB_DIGITS], const uint8_t s[32]) {
    const uint32_t mask = (1u << AMA_ED25519_COMB_WINDOW) - 1u;
    const int32_t half = (int32_t)1 << (AMA_ED25519_COMB_WINDOW - 1);
    int32_t carry = 0;
    int i;

    for (i = 0; i < AMA_ED25519_COMB_DIGITS; i++) {
        const int bit = i * AMA_ED25519_COMB_WINDOW;
        const int byte = bit >> 3;
        const int shift = bit & 7;
        uint32_t v = (uint32_t)s[byte];
        if (byte + 1 < 32) {
            v |= (uint32_t)s[byte + 1] << 8;
        }
        e[i] = (int8_t)((v >> shift) & mask);
    }
    for (i = 0; i < AMA_ED25519_COMB_DIGITS - 1; i++) {
        int32_t v = (int32_t)e[i] + carry;
        carry = (v + half) >> AMA_ED25519_COMB_WINDOW;   /* 0 or 1 */
        e[i] = (int8_t)(v - (carry << AMA_ED25519_COMB_WINDOW));
    }
    e[AMA_ED25519_COMB_DIGITS - 1] = (int8_t)((int32_t)e[AMA_ED25519_COMB_DIGITS - 1] + carry);
}

/* Width-w wNAF expansion of a 32-byte scalar: 256 signed digits, each odd in
 * [-(2^(w-1) - 1), 2^(w-1) - 1] or zero.  PUBLIC scalars only — the digit
 * extraction is variable-time by construction.
 *
 * The scalar is reduced mod l first, and the reduction is load-bearing, not
 * hygiene.  A width-w wNAF of a 256-bit integer needs up to 257 digits, and
 * the compensation step for a negative digit ADDS to the running value, so a
 * digit selected near the top of an unreduced scalar carries out of limb 7.
 * With 256 slots and eight 32-bit limbs that carry was discarded and the
 * 257th digit never emitted, so the recoding silently represented s - 2^256
 * for ~17% of uniform 32-byte scalars — ff..ff recoded as -1 and
 * ama_ed25519_scalarmult_public(out, ff..ff, B) returned -B with AMA_SUCCESS.
 * After reducing, s < l < 2^253: at most 254 digits, the running value stays
 * below 2^254, and neither the slot count nor the limb count can overflow. */
static void sc25519_to_wnaf(int8_t wnaf[256], const uint8_t scalar[32], int w) {
    uint32_t s[8];
    uint8_t reduced[32];
    int i, pos;
    const uint32_t mask = ((uint32_t)1 << w) - 1u;
    const int32_t half = (int32_t)1 << (w - 1);
    const int32_t full = (int32_t)1 << w;

    sc25519_reduce32(reduced, scalar);
    for (i = 0; i < 8; i++) {
        s[i] = (uint32_t)reduced[4 * i]
             | ((uint32_t)reduced[4 * i + 1] << 8)
             | ((uint32_t)reduced[4 * i + 2] << 16)
             | ((uint32_t)reduced[4 * i + 3] << 24);
    }
    for (pos = 0; pos < 256; pos++) {
        int32_t digit = 0;
        if (s[0] & 1u) {
            digit = (int32_t)(s[0] & mask);
            if (digit >= half) digit -= full;
            if (digit < 0) {
                uint64_t carry = (uint64_t)(uint32_t)(-digit);
                for (i = 0; i < 8; i++) {
                    carry += (uint64_t)s[i];
                    s[i] = (uint32_t)carry;
                    carry >>= 32;
                }
            } else {
                uint64_t borrow = 0;
                uint64_t sub = (uint64_t)(uint32_t)digit;
                for (i = 0; i < 8; i++) {
                    uint64_t val = (uint64_t)s[i] - sub - borrow;
                    s[i] = (uint32_t)val;
                    borrow = (val >> 63) & 1;
                    sub = 0;
                }
            }
        }
        wnaf[pos] = (int8_t)digit;
        for (i = 0; i < 7; i++) {
            s[i] = (s[i] >> 1) | (s[i + 1] << 31);
        }
        s[7] >>= 1;
    }
}

/* ============================================================================
 * GROUP-LEVEL HELPERS (radix-independent glue around the dispatch)
 * ============================================================================ */

/* out = [s]B in constant time, for any 32-byte s (reduced mod l here). */
static void ed25519_scalarmult_base(uint8_t out[32], const uint8_t s[32]) {
    uint8_t reduced[32];
    int8_t e[AMA_ED25519_COMB_DIGITS];
    sc25519_reduce32(reduced, s);
    ed25519_comb_digits(e, reduced);
    ED_DISPATCH(ama_ed25519_ge_scalarmult_base, out, e);
    ama_secure_memzero(reduced, sizeof reduced);
    ama_secure_memzero(e, sizeof e);
}

/* ============================================================================
 * ED25519 API FUNCTIONS
 * ============================================================================ */

/**
 * Generate Ed25519 keypair
 *
 * @param public_key Output: 32-byte public key
 * @param secret_key In/out: seed in [0..31] (caller-provided), public key
 *                   written to [32..63]
 * @return AMA_SUCCESS or error code
 */
ama_error_t ama_ed25519_keypair(uint8_t public_key[32], uint8_t secret_key[64]) {
    uint8_t hash[64];

    if (!public_key || !secret_key) {
        return AMA_ERROR_INVALID_PARAM;
    }

    /* Hash the seed (caller must provide seed in secret_key[0..31]) */
    sha512(secret_key, 32, hash);

    /* Clamp the scalar */
    hash[0] &= 248;
    hash[31] &= 127;
    hash[31] |= 64;

    /* A = [a]B */
    ed25519_scalarmult_base(public_key, hash);

    /* Store public key in secret_key[32..63] */
    memcpy(secret_key + 32, public_key, 32);

    ama_secure_memzero(hash, sizeof(hash));
    return AMA_SUCCESS;
}

/**
 * Sign a message with Ed25519
 *
 * @param signature Output: 64-byte signature
 * @param message Message to sign
 * @param message_len Length of message
 * @param secret_key 64-byte secret key
 * @return AMA_SUCCESS or error code
 */
ama_error_t ama_ed25519_sign(
    uint8_t signature[64],
    const uint8_t *message,
    size_t message_len,
    const uint8_t secret_key[64]
) {
    uint8_t hash[64];
    uint8_t r[64];
    uint8_t hram[64];
    /* Stack buffer for messages <= ED25519_STACK_THRESHOLD (4KB).
     * Eliminates malloc/free overhead for >99% of real-world messages.
     * Only heap-allocate for unusually large messages. */
    uint8_t stack_buf[64 + ED25519_STACK_THRESHOLD];
    uint8_t *buf;
    int buf_on_heap = 0;

    if (!signature || !secret_key || (!message && message_len > 0)) {
        return AMA_ERROR_INVALID_PARAM;
    }

    /* Hash the secret key */
    sha512(secret_key, 32, hash);
    hash[0] &= 248;
    hash[31] &= 127;
    hash[31] |= 64;

    /* Determine buffer allocation: use stack for small messages.
     * Compare against the threshold directly to avoid size_t overflow
     * in (64 + message_len) when message_len is near SIZE_MAX. */
    if (message_len <= ED25519_STACK_THRESHOLD) {
        buf = stack_buf;
    } else {
        /* Both early exits fire AFTER the expansion above, so `hash`
         * already holds the clamped secret scalar and the PRF key —
         * scrub it on the way out (INVARIANT-6). */
        if (message_len > SIZE_MAX - 64) {
            ama_secure_memzero(hash, sizeof(hash));
            return AMA_ERROR_INVALID_PARAM;
        }
        buf = (uint8_t *)malloc(64 + message_len);
        if (!buf) {
            ama_secure_memzero(hash, sizeof(hash));
            return AMA_ERROR_MEMORY;
        }
        buf_on_heap = 1;
    }

    /* r = H(h[32..63] || message) mod L */
    memcpy(buf, hash + 32, 32);
    if (message_len > 0) {
        memcpy(buf + 32, message, message_len);
    }
    sha512(buf, 32 + message_len, r);
    sc25519_reduce(r);

    /* R = [r]B */
    ed25519_scalarmult_base(signature, r);

    /* H(R || A || message) — reuse the same buffer (64 + msg_len >= 32 + msg_len) */
    memcpy(buf, signature, 32);
    memcpy(buf + 32, secret_key + 32, 32);
    if (message_len > 0) {
        memcpy(buf + 64, message, message_len);
    }
    sha512(buf, 64 + message_len, hram);
    sc25519_reduce(hram);

    /* s = r + H(R||A||M) * a mod L */
    sc25519_muladd(signature + 32, r, hram, hash);

    /* Cleanup — scrub all sensitive intermediates */
    ama_secure_memzero(hash, sizeof(hash));
    ama_secure_memzero(r, sizeof(r));
    ama_secure_memzero(hram, sizeof(hram));
    ama_secure_memzero(buf, 64 + message_len);
    if (buf_on_heap) {
        free(buf);
    }

    return AMA_SUCCESS;
}

/**
 * Verify an Ed25519 signature
 *
 * @param signature 64-byte signature
 * @param message Message to verify
 * @param message_len Length of message
 * @param public_key 32-byte public key
 * @return AMA_SUCCESS if valid, AMA_ERROR_VERIFY_FAILED if invalid
 */
ama_error_t ama_ed25519_verify(
    const uint8_t signature[64],
    const uint8_t *message,
    size_t message_len,
    const uint8_t public_key[32]
) {
    uint8_t h[64];
    /* Stack buffer for messages <= ED25519_STACK_THRESHOLD (4KB). */
    uint8_t stack_buf[64 + ED25519_STACK_THRESHOLD];
    uint8_t *buf;
    int buf_on_heap = 0;

    if (!signature || !public_key || (!message && message_len > 0)) {
        return AMA_ERROR_INVALID_PARAM;
    }

    /* RFC 8032 §5.1.7: S must decode in the range 0 <= S < L, and a
     * signature whose S falls outside it is invalid.
     *
     * This check is load-bearing on this path, not belt-and-braces: the
     * scalar recoding below canonicalises its input mod l, so S and S + L
     * produce the identical point and both satisfy the group equation.
     * Without this, (R, S + L) verifies wherever (R, S) does.  Wycheproof
     * tc63/tc85.  See internal/ama_ed25519_canonical.h. */
    if (!ama_ed25519_signature_s_is_canonical(signature)) {
        return AMA_ERROR_VERIFY_FAILED;
    }

    /* RFC 8032 §5.1.7 step 1 also says to DECODE the first half as a point,
     * and §5.1.3 is what decoding means: y >= p fails, and x = 0 with the
     * sign bit set fails.  The re-encode comparison at the bottom could never
     * match a non-canonical R anyway, since the encoder emits only canonical
     * encodings; stating the rule costs one byte predicate on a public input
     * and puts the batch path — a loop over this function — on the same
     * stated rule rather than on an accident of the encoder's range. */
    if (!ama_ed25519_signature_r_is_canonical(signature)) {
        return AMA_ERROR_VERIFY_FAILED;
    }

    /* h = H(R || A || message) mod l — stack allocation for small messages.
     * Compare against the threshold directly to avoid size_t overflow
     * in (64 + message_len) when message_len is near SIZE_MAX. */
    if (message_len <= ED25519_STACK_THRESHOLD) {
        buf = stack_buf;
    } else {
        if (message_len > SIZE_MAX - 64) {
            return AMA_ERROR_INVALID_PARAM;
        }
        buf = (uint8_t *)malloc(64 + message_len);
        if (!buf) {
            return AMA_ERROR_MEMORY;
        }
        buf_on_heap = 1;
    }
    memcpy(buf, signature, 32);
    memcpy(buf + 32, public_key, 32);
    if (message_len > 0) {
        memcpy(buf + 64, message, message_len);
    }
    sha512(buf, 64 + message_len, h);
    sc25519_reduce(h);
    ama_secure_memzero(buf, 64 + message_len);
    if (buf_on_heap) {
        free(buf);
    }

    /* Check [s]B - R - [h]A = O.  The group check runs in the half-size
     * form of internal/ama_ed25519_halfsize.h: (v0, v1) with v1 ≡ v0 h
     * (mod 8l) and v0 odd, v2 = v0 s mod l split into 128-bit halves k0, k1,
     * and one ladder of about 128 doublings over
     *
     *     [k0]B + [k1](2^128 B) - [v0]R - [v1]A,
     *
     * which is v0 ([s]B - R - [h]A) exactly and vanishes iff the direct check
     * does (the header proves it, including the small-order and mixed-order
     * cases).  Every scalar is public (s from the signature, h from a hash
     * of public data), so the variable-time reduction, recoding and ladder
     * are safe; R and A are decoded inside the backend, which refuses a
     * non-canonical or off-curve encoding.  R's canonical form was checked
     * above, and decoding it rather than re-encoding the recomputed point is
     * an equivalent test because canonical encodings are unique. */
    {
        static const uint8_t zero[32] = {0};
        uint8_t v0[32], v1[32], v2[32], k0[32], k1[32];
        int8_t w_v0[AMA_ED25519_WNAF_SLOTS], w_v1[AMA_ED25519_WNAF_SLOTS];
        int8_t w_k0[AMA_ED25519_WNAF_SLOTS], w_k1[AMA_ED25519_WNAF_SLOTS];
        int v1_negative, top, t, rc;

        ama_ed25519_half_reduce(v0, v1, &v1_negative, h);
        sc25519_muladd(v2, zero, v0, signature + 32);       /* v2 = v0 s mod l */
        memcpy(k0, v2, 16);
        memset(k0 + 16, 0, 16);
        memcpy(k1, v2 + 16, 16);
        memset(k1 + 16, 0, 16);
        top = ama_ed25519_wnaf_bytes(w_v0, AMA_ED25519_WNAF_SLOTS, v0, 5);
        t = ama_ed25519_wnaf_bytes(w_v1, AMA_ED25519_WNAF_SLOTS, v1, 5);
        if (t > top) top = t;
        t = ama_ed25519_wnaf_bytes(w_k0, AMA_ED25519_WNAF_SLOTS, k0, AMA_ED25519_BASE_ODD_WINDOW);
        if (t > top) top = t;
        t = ama_ed25519_wnaf_bytes(w_k1, AMA_ED25519_WNAF_SLOTS, k1, AMA_ED25519_BASE_ODD_WINDOW);
        if (t > top) top = t;
        rc = ED_DISPATCH(ama_ed25519_ge_verify_half, signature, public_key, w_v0, w_v1,
                         v1_negative, w_k0, w_k1, top);
        return (rc == 1) ? AMA_SUCCESS : AMA_ERROR_VERIFY_FAILED;
    }
}

/**
 * Batch verify multiple Ed25519 signatures.
 *
 * vartime: safe for verification where all scalars are public.
 * Each entry is verified independently; results[i] = 1 if valid, 0 if invalid.
 *
 * @param entries  Array of batch entries
 * @param count    Number of entries
 * @param results  Output: 1=valid, 0=invalid per entry
 * @return AMA_SUCCESS if all valid, AMA_ERROR_VERIFY_FAILED if any invalid,
 *         AMA_ERROR_INVALID_PARAM on NULL inputs
 *
 * `results` is zeroed before any entry is verified, so every slot is written
 * on every path that gets past the argument checks — see the public contract
 * in include/ama_cryptography.h.
 */
ama_error_t ama_ed25519_batch_verify(
    const ama_ed25519_batch_entry *entries,
    size_t count,
    int *results
) {
    size_t i;
    int all_valid = 1;

    if (!entries || !results) {
        return AMA_ERROR_INVALID_PARAM;
    }
    if (count == 0) {
        return AMA_SUCCESS;
    }

    /* Oversized-count rejection, BEFORE the pre-zero loop below.  The public
     * contract in include/ama_cryptography.h states the rejection in terms of
     * `results`: a `count` large enough to wrap `count * sizeof(void *)`
     * cannot describe a real array, so walking `results[0..count)` would
     * itself be the wild write.  The thresholds are part of the published
     * argument contract and must not move without it. */
    if (count > SIZE_MAX / sizeof(const unsigned char *) ||
        count > SIZE_MAX / sizeof(size_t)) {
        return AMA_ERROR_INVALID_PARAM;
    }

    /* `results` is fully written before any per-entry work, so no path can
     * leave a stale 1 from an earlier batch visible to a caller that reads
     * the array before the return code: a verifier fails towards "invalid". */
    for (i = 0; i < count; i++) {
        results[i] = 0;
    }

    /* Per-entry verification, unconditionally.  The only way a batch
     * verifier cannot disagree with the single verifier on the same 64 bytes
     * is to BE the single verifier, per entry: a randomised aggregate decides
     * a different predicate (it accepts canonically encoded small-order
     * residues with probability ~1/ord), which is the defect B1 of the 5.0.0
     * pre-tag audit removed. */
    for (i = 0; i < count; i++) {
        ama_error_t rc = ama_ed25519_verify(
            entries[i].signature,
            entries[i].message,
            entries[i].message_len,
            entries[i].public_key
        );
        results[i] = (rc == AMA_SUCCESS) ? 1 : 0;
        if (!results[i]) {
            all_valid = 0;
        }
    }
    return all_valid ? AMA_SUCCESS : AMA_ERROR_VERIFY_FAILED;
}

/* ======================================================================
 * EXPOSED PRIMITIVES FOR FROST / THRESHOLD SIGNATURES
 *
 * These functions expose the group operations to ama_frost.c without
 * breaking encapsulation of the internal types.  All compressed points
 * are 32-byte little-endian Y||sign(X).
 * ====================================================================== */

/**
 * Raw scalar-basepoint multiplication: point = scalar * G.
 *
 * Unlike ama_ed25519_keypair() this does NOT hash or clamp the scalar;
 * the 32-byte little-endian scalar is used verbatim (reduced mod l).  This
 * is the primitive required by FROST (RFC 9591) and any other Schnorr-like
 * protocol that needs algebraic linearity:
 *   point_from_scalar(a) + point_from_scalar(b) == point_from_scalar(a+b)
 *
 * Constant-time in the scalar.
 *
 * @param point   Output: 32-byte compressed Ed25519 point
 * @param scalar  Input:  32-byte little-endian scalar
 * @return AMA_SUCCESS, or AMA_ERROR_INVALID_PARAM if either pointer is NULL.
 */
AMA_API ama_error_t ama_ed25519_point_from_scalar(uint8_t point[32],
                                                  const uint8_t scalar[32]) {
    /* BREAKING in 4.0.0: returns ama_error_t so a NULL argument is an error
     * rather than a segfault.  See include/ama_cryptography.h. */
    if (!point || !scalar) return AMA_ERROR_INVALID_PARAM;
    ed25519_scalarmult_base(point, scalar);
    return AMA_SUCCESS;
}

/**
 * Point addition: result = P + Q (compressed Ed25519 points).
 *
 * @param result  Output: 32-byte compressed point
 * @param p       Input:  32-byte compressed point P
 * @param q       Input:  32-byte compressed point Q
 * @return AMA_SUCCESS on success, error if decompression fails
 */
AMA_API ama_error_t ama_ed25519_point_add(uint8_t result[32],
                                          const uint8_t p[32],
                                          const uint8_t q[32]) {
    if (!result || !p || !q) return AMA_ERROR_INVALID_PARAM;
    if (ED_DISPATCH(ama_ed25519_ge_point_add, result, p, q) != 0) {
        return AMA_ERROR_INVALID_PARAM;
    }
    return AMA_SUCCESS;
}

/**
 * Variable-time scalar-point multiplication: result = public_scalar * P.
 *
 * SECURITY: NOT constant-time.  The scalar MUST be PUBLIC data
 * (e.g., FROST binding factors, verification challenges).
 * Do NOT use with secret scalars — use ama_ed25519_point_from_scalar
 * for secret-scalar × basepoint operations.
 *
 * Renamed from ama_ed25519_scalar_mult (audit finding C7) to make the
 * public-only constraint impossible to miss.
 *
 * @param result        Output: 32-byte compressed point
 * @param public_scalar Input:  32-byte little-endian PUBLIC scalar
 * @param point         Input:  32-byte compressed point P
 * @return AMA_SUCCESS on success, error if decompression fails
 */
AMA_API ama_error_t ama_ed25519_scalarmult_public(uint8_t result[32],
                                                  const uint8_t public_scalar[32],
                                                  const uint8_t point[32]) {
    int8_t wnaf[256];
    if (!result || !public_scalar || !point) return AMA_ERROR_INVALID_PARAM;
    sc25519_to_wnaf(wnaf, public_scalar, 5);
    if (ED_DISPATCH(ama_ed25519_ge_scalarmult_vartime, result, wnaf, point) != 0) {
        return AMA_ERROR_INVALID_PARAM;
    }
    return AMA_SUCCESS;
}

/**
 * Joint variable-time double-base scalar multiplication using the
 * Shamir/Straus trick: result = [s1]P1 + [s2]P2 in one interleaved pass.
 *
 * SECURITY: NOT constant-time.  Both scalars MUST be PUBLIC data
 * (Ed25519 verify, batch verify, FROST verifier).  Do NOT use with
 * secret scalars — wNAF digit extraction and table indexing leak the
 * scalars via timing side-channels.
 *
 * @param result  Output: 32-byte compressed Edwards point [s1]P1 + [s2]P2
 * @param s1      Input:  32-byte little-endian PUBLIC scalar
 * @param P1      Input:  32-byte compressed Edwards point
 * @param s2      Input:  32-byte little-endian PUBLIC scalar
 * @param P2      Input:  32-byte compressed Edwards point
 * @return AMA_SUCCESS on success,
 *         AMA_ERROR_INVALID_PARAM on NULL inputs or point decompression failure.
 */
AMA_API ama_error_t ama_ed25519_double_scalarmult_public(
    uint8_t result[32],
    const uint8_t s1[32], const uint8_t P1[32],
    const uint8_t s2[32], const uint8_t P2[32]) {
    int8_t w1[256], w2[256];
    if (!result || !s1 || !P1 || !s2 || !P2) return AMA_ERROR_INVALID_PARAM;
    sc25519_to_wnaf(w1, s1, 5);
    sc25519_to_wnaf(w2, s2, 5);
    if (ED_DISPATCH(ama_ed25519_ge_double_scalarmult_vartime, result, w1, P1, w2, P2) != 0) {
        return AMA_ERROR_INVALID_PARAM;
    }
    return AMA_SUCCESS;
}

/**
 * Reduce a 64-byte scalar modulo the Ed25519 group order l.
 * Input: 64-byte little-endian integer. Output written to first 32 bytes.
 *
 * @param s  In/out: 64-byte buffer, reduced result in s[0..31]
 */
AMA_API void ama_ed25519_sc_reduce(uint8_t s[64]) {
    sc25519_reduce(s);
}

/**
 * Scalar multiply-add: s = (a + b * c) mod l.
 * All inputs/output are 32-byte little-endian scalars.
 *
 * @param s  Output: 32-byte scalar
 * @param a  Input:  32-byte scalar
 * @param b  Input:  32-byte scalar
 * @param c  Input:  32-byte scalar
 */
AMA_API void ama_ed25519_sc_muladd(uint8_t s[32],
                           const uint8_t a[32],
                           const uint8_t b[32],
                           const uint8_t c[32]) {
    sc25519_muladd(s, a, b, c);
}

/**
 * SHA-512 hash (exposed for FROST challenge computation).
 * Wraps the internal ama_sha512 from internal/ama_sha2.h so that
 * other TUs (ama_frost.c) don't need to include the header-only
 * implementation (which pulls in unused static functions).
 */
AMA_API void ama_ed25519_sha512(const uint8_t *data, size_t len,
                                uint8_t out[64]) {
    sha512(data, len, out);
}

#ifdef AMA_TESTING_MODE
/* Test-only: the table geometry of a backend (0 = fe51, 1 = fe64-mulx), so
 * tests/c/test_ed25519_static_tables.c can walk every entry without including
 * the generated header.  -1 for a backend this build does not carry. */
int ama_ed25519_test_table_geometry(int backend, int *tables, int *entries,
                                    int *stride_bits, int *odd_count, int *odd_shift) {
    if (backend != 0) {
#if defined(AMA_HAVE_ED25519_FE64_MULX_IMPL)
        /* The MULX unit issues BMI2/ADX unconditionally; report it absent when
         * the host cannot run it, so the test skips backend 1 instead of
         * taking SIGILL on a BMI2-without-ADX core. */
        if (backend != 1 || !ama_cpuid_has_x25519_mulx()) return -1;
#else
        return -1;
#endif
    }
    *tables = AMA_ED25519_COMB_TABLES;
    *entries = AMA_ED25519_COMB_ENTRIES;
    *stride_bits = AMA_ED25519_COMB_STRIDE_BITS;
    *odd_count = AMA_ED25519_BASE_ODD_COUNT;
    *odd_shift = AMA_ED25519_BASE_ODD_SHIFT;
    return 0;
}

/* Test-only: compressed encoding of a static table entry of the selected
 * backend (0 = fe51, 1 = fe64-mulx), so tests/c/test_ed25519_static_tables.c
 * can check the committed constants against the variable-base arithmetic.
 * Returns -1 for a backend this build does not carry or a bad index. */
int ama_ed25519_test_table_entry(int backend, int which, int i, int j, uint8_t out[32]) {
    if (backend == 0) {
        return ama_ed25519_ge_table_entry_fe51(which, i, j, out);
    }
#if defined(AMA_HAVE_ED25519_FE64_MULX_IMPL)
    if (backend == 1 && ama_cpuid_has_x25519_mulx()) {
        return ama_ed25519_ge_table_entry_mulx(which, i, j, out);
    }
#endif
    return -1;
}
#endif /* AMA_TESTING_MODE */
