#!/usr/bin/env python3
# Copyright (C) 2025-2026 Steel Security Advisors LLC
# SPDX-License-Identifier: Apache-2.0
"""
INVARIANT-36 — no third-party cryptographic implementation in the validation path.

AMA is built from standardised primitives and its own code. That commitment is
stated in the README ("no custom ciphers ... zero external crypto deps") and it
holds for what the library *ships*: nothing links, loads or calls another
cryptographic library at runtime.

It did not hold for how the library was *checked*. The key-format conformance
corpus carried twelve PEM files generated by OpenSSL, vendored as the answer key
for EC PKCS#8 and SPKI on the reasoning that RFC 5915 and RFC 5480 publish no
worked examples. The files were static data and no build or test invoked
OpenSSL — but a competing implementation's output was nonetheless the thing
AMA's correctness was measured against, in AMA's own repository.

Two problems with that, one of principle and one of engineering:

* A project whose stated position is that it depends on no other cryptographic
  implementation should not depend on one to know whether it is right.
* An answer key taken from an implementation inherits that implementation's
  opinions, including its bugs and its non-conformances. A specification's
  worked example does not. This is the same lesson PR #378 learned on RFC 6979,
  where an "independent" reference normalised `s` because the C code did, and
  the two agreed by construction while both diverged from the RFC.

RFC 9500 §2.3 ("Standard Public Key Cryptography (PKCS) Test Keys", December
2023) publishes exactly the EC keys that gap needed, and
``tests/ref_keyformat.py`` supplies a second encoder written from the RFCs' own
ASN.1 for everything the documents do not print. The OpenSSL corpus is gone.

This checker is what stops it coming back, because "just this once, to cover a
gap" is precisely how it arrived.

What is checked
---------------
1. **No test or development tool invokes an external cryptographic binary.**
   ``openssl``, ``gpg``, ``certtool``, ``pkcs11-tool`` and friends, in any
   ``subprocess`` call or shell string under ``ama_cryptography/``,
   ``tests/`` or ``tools/``. The shipped package is scanned first and for
   the strongest reason: INVARIANT-1 says the core package "must not
   import or call" a third-party cryptographic implementation *at
   runtime*, which is a stronger claim than anything about how AMA is
   checked.
2. **Every vendored key-format record names a standards-body source.** The
   ``source.url`` of each corpus file must be on ``rfc-editor.org`` or
   ``ietf.org``.
3. **The reference encoder stays independent.** ``tests/ref_keyformat.py`` must
   import nothing from ``ama_cryptography`` — a reference that imports the
   encoder it checks agrees with it by construction and proves nothing.

What is deliberately *not* checked
----------------------------------
* ``wycheproof_vectors/`` and ``tests/kat/``'s NIST ACVP corpora. These are
  published *test-vector suites* — adversarial inputs with expected verdicts —
  not another implementation's key output presented as ground truth. Their
  provenance has its own gates (``tools/refresh_wycheproof_corpus.py`` and
  ``.github/workflows/corpus-provenance.yml``).
* Naming a competing implementation. Curve aliases like ``prime256v1`` are
  wire-format spellings AMA must *accept*; a comment crediting where an
  approach came from is scholarship. Only an invocation is a violation, and
  the check works on the AST so prose cannot trip it.

``ama_cryptography/legacy_compat.py`` used to be a recorded exception here:
it shelled out to ``openssl ts`` to build and verify RFC 3161 timestamps.
That was an INVARIANT-1 violation in the shipped tree, and it is gone —
``rfc3161_timestamp.py`` now encodes the ``TimeStampReq`` and decodes the
``TimeStampResp``/``TSTInfo`` with AMA's own DER codec. The exception is
removed rather than reworded, and the package is inside the scan so it
cannot come back quietly.

Exit code:
    0  no third-party cryptographic implementation in the validation path
    1  a violation was found
"""

from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

#: Executables that are another cryptographic implementation. Matched as whole
#: words so a filename like `openssl_notes.md` or a variable named `gpg_path`
#: does not trip the check — only an actual invocation does.
CRYPTO_BINARIES = (
    "openssl",
    "gpg",
    "gpg2",
    "certtool",
    "pkcs11-tool",
    "keytool",
    "libressl",
    "boringssl",
    "nss-tool",
    "certutil",
)

#: Hosts a vendored answer key may come from: the RFC archive and the IETF's.
STANDARDS_HOSTS = ("rfc-editor.org", "ietf.org")

#: Trees scanned for invocations. `ama_cryptography/` is the shipped package
#: and carries the strongest form of the rule (INVARIANT-1: no third-party
#: cryptographic implementation called at runtime), so it is scanned first.
SCAN_ROOTS = ("ama_cryptography", "tests", "tools")

KEYFORMAT_CORPUS = REPO / "tests" / "kat" / "keyformats"
REFERENCE_ENCODER = REPO / "tests" / "ref_keyformat.py"

_BINARY_RE = re.compile(r"\b(" + "|".join(CRYPTO_BINARIES) + r")\b")


def _rel(path: Path) -> str:
    """Repo-relative when the path is in the tree, absolute otherwise.

    The scan functions take a root so the tests can drive them over a temporary
    tree; those paths are outside the repository, and ``relative_to`` raises on
    them. Mirrors ``tools/check_version_consistency.py``.
    """
    try:
        return str(path.relative_to(REPO))
    except ValueError:
        return str(path)


#: Every way of starting a process that this checker recognises.
#:
#: ``system`` was already here — i.e. the intent to cover ``os``'s shell-out
#: helpers was explicit — but ``popen`` was not, and neither were
#: ``getoutput``/``getstatusoutput`` or the ``exec*``/``spawn*`` family. A
#: one-line ``os.popen("openssl ...")`` shim walked past a gate whose whole
#: purpose is to stop exactly that.
_SPAWN_NAMES = frozenset(
    {
        "run",
        "Popen",
        "call",
        "check_call",
        "check_output",
        "system",
        "popen",
        "getoutput",
        "getstatusoutput",
        "execl",
        "execle",
        "execlp",
        "execlpe",
        "execv",
        "execve",
        "execvp",
        "execvpe",
        "spawnl",
        "spawnle",
        "spawnlp",
        "spawnlpe",
        "spawnv",
        "spawnve",
        "spawnvp",
        "spawnvpe",
        "posix_spawn",
        "posix_spawnp",
        "create_subprocess_exec",
        "create_subprocess_shell",
    }
)


def _module_string_constants(tree: ast.AST) -> dict[str, list[str]]:
    """Module- and function-level ``NAME = "..."`` / ``NAME = [...]`` bindings.

    Without this the scan sees only strings written *lexically inside* the
    call, so::

        CMD = ["openssl", "genpkey", ...]
        subprocess.run(CMD, check=True)

    passed cleanly — and that is not a hypothetical spelling, it is the one the
    removed generator actually used (``cmd_query = ["openssl", "ts", ...]``
    then ``subprocess.run(cmd_query, ...)``). A gate that would not have caught
    the code it exists to prevent returning is not a gate.

    A flat, whole-file table rather than real scope analysis: the question is
    "does a crypto binary name reach a spawn call", and a name bound anywhere
    in the file is close enough to answer it conservatively.
    """
    table: dict[str, list[str]] = {}
    for node in ast.walk(tree):
        targets: list[ast.expr] = []
        if isinstance(node, ast.Assign):
            targets = list(node.targets)
            value: ast.expr = node.value
        elif isinstance(node, ast.AnnAssign) and node.value is not None:
            targets = [node.target]
            value = node.value
        else:
            continue
        strings = [
            child.value
            for child in ast.walk(value)
            if isinstance(child, ast.Constant) and isinstance(child.value, str)
        ]
        if not strings:
            continue
        for target in targets:
            if isinstance(target, ast.Name):
                table.setdefault(target.id, []).extend(strings)
    return table


def _literal_strings(node: ast.AST, bindings: dict[str, list[str]] | None = None) -> list[str]:
    """Every string constant reachable from an expression tree.

    Covers ``["openssl", "genpkey"]``, ``"openssl genpkey"``, the elements of a
    starred list — which is how the removed generator actually spelled it — and,
    when ``bindings`` is supplied, any ``ast.Name`` bound to a string or a list
    of strings elsewhere in the same file.
    """
    out: list[str] = []
    for child in ast.walk(node):
        if isinstance(child, ast.Constant) and isinstance(child.value, str):
            out.append(child.value)
        elif bindings is not None and isinstance(child, ast.Name):
            out.extend(bindings.get(child.id, ()))
    return out


def scan_for_binary_invocations(repo: Path = REPO) -> list[str]:
    """Find calls that would run another cryptographic implementation.

    Works on the AST rather than by grepping, so a mention in a docstring or a
    comment — of which this repository has many, mostly of the form "replaces
    OpenSSL X" — is not a finding. Only the arguments of a call are inspected.
    """
    problems: list[str] = []
    for root in SCAN_ROOTS:
        base = repo / root
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*.py")):
            if any(part in {"__pycache__", "build"} for part in path.parts):
                continue
            rel = _rel(path)
            try:
                tree = ast.parse(path.read_text(encoding="utf-8"))
            except (SyntaxError, UnicodeDecodeError) as exc:  # pragma: no cover
                problems.append(f"{rel}: could not parse ({exc})")
                continue
            bindings = _module_string_constants(tree)
            for node in ast.walk(tree):
                if not isinstance(node, ast.Call):
                    continue
                target = node.func
                name = (
                    target.attr
                    if isinstance(target, ast.Attribute)
                    else target.id if isinstance(target, ast.Name) else ""
                )
                if name not in _SPAWN_NAMES:
                    continue
                for text in _literal_strings(node, bindings):
                    match = _BINARY_RE.search(text)
                    if match:
                        problems.append(
                            f"{rel}:{node.lineno}: invokes {match.group(1)!r}. "
                            "AMA's correctness is not measured against another "
                            "cryptographic implementation (INVARIANT-36); use a "
                            "published specification vector or "
                            "tests/ref_keyformat.py."
                        )
                        break
    return problems


def scan_corpus_sources(corpus: Path = KEYFORMAT_CORPUS) -> list[str]:
    """Every vendored record must trace to a standards document."""
    problems: list[str] = []
    if not corpus.is_dir():
        return [f"{corpus} is missing"]
    files = sorted(corpus.glob("*.json"))
    if not files:
        return [f"{corpus} contains no corpus files"]
    for path in files:
        rel = _rel(path)
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            problems.append(f"{rel}: not valid JSON ({exc})")
            continue
        url = str(data.get("source", {}).get("url", ""))
        if not any(host in url for host in STANDARDS_HOSTS):
            problems.append(
                f"{rel}: source.url is {url!r}, which is not a standards-body "
                f"archive ({', '.join(STANDARDS_HOSTS)}). A vendored answer key "
                "must be a specification's own worked example."
            )
    # A directory under the corpus is how the OpenSSL files were carried.
    for child in sorted(corpus.iterdir()):
        if child.is_dir():
            problems.append(
                f"{_rel(child)}: unexpected directory in the corpus. "
                "Every record lives in a JSON file naming the document it came "
                "from; a directory of key files is how third-party material "
                "entered this tree before."
            )
    return problems


def check_reference_encoder(path: Path = REFERENCE_ENCODER) -> list[str]:
    """The reference must stand on the specification, not on the code it checks."""
    if not path.is_file():
        return [
            f"{_rel(path)} is missing; it is what replaced the "
            "third-party corpus and the tests depend on it"
        ]
    imported: set[str] = set()
    for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
        if isinstance(node, ast.Import):
            imported.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported.add(node.module.split(".")[0])
    if "ama_cryptography" in imported:
        return [
            f"{_rel(path)} imports ama_cryptography. A reference that "
            "imports the encoder it checks agrees with it by construction and "
            "proves nothing — the RFC 6979 lesson, in one line of import."
        ]
    return []


#: Vector corpora AMA validates itself against.  Their expected values must be
#: TRANSCRIBED from a specification or produced by AMA's own reference encoder
#: — never computed by another implementation at generation time.
VECTOR_ROOTS = ("nist_vectors",)

#: Standard-library hash and HMAC constructors.  On any libcrypto-linked
#: CPython — every manylinux wheel and every mainstream distribution Python,
#: as ``tools/check_stdlib_hash_boundary.py``'s docstring states — these ARE
#: OpenSSL.  A generator that computes an expected digest with one of them
#: writes OpenSSL's output into a file labelled with a NIST publication, and
#: the run then validates AMA against it.
_STDLIB_DIGEST_CALLS = (
    "hashlib.sha1",
    "hashlib.sha224",
    "hashlib.sha256",
    "hashlib.sha384",
    "hashlib.sha512",
    "hashlib.sha3_224",
    "hashlib.sha3_256",
    "hashlib.sha3_384",
    "hashlib.sha3_512",
    "hashlib.shake_128",
    "hashlib.shake_256",
    "hashlib.blake2b",
    "hashlib.blake2s",
    "hashlib.md5",
    "hashlib.new",
    "hashlib.pbkdf2_hmac",
    "hmac.new",
    "hmac.digest",
)

#: The modules those calls live in.  Refused outright in a vector generator.
_STDLIB_DIGEST_MODULES = frozenset({"hashlib", "hmac", "_hashlib"})


def _dotted_call_name(node: ast.Call) -> str | None:
    func = node.func
    if isinstance(func, ast.Attribute) and isinstance(func.value, ast.Name):
        return f"{func.value.id}.{func.attr}"
    return None


def scan_vector_generators(repo: Path = REPO) -> list[str]:
    """No expected value in a vector corpus may be computed by the stdlib.

    ``nist_vectors/fetch_vectors.py`` wrote ``SHA-256-FIPS180-4.json`` with
    ``"source": "FIPS 180-4 Section B.1"`` and every digest in it produced by
    ``hashlib.sha256(...).hexdigest()`` at generation time, and
    ``nist_vectors/run_vectors.py`` validated AMA's SHA-256 against that file.
    So on every regeneration the "NIST vectors" were OpenSSL's output wearing a
    NIST label: a differential test against another implementation, presented
    as conformance to a specification, in the one place this invariant exists
    to keep clean.  The committed values happened to be right; where the next
    regeneration would have got them was not.

    The scan is over the GENERATORS rather than the JSON, because a digest in
    a committed file carries no evidence of where it came from — which is
    precisely how this survived.

    Two rules, not one.  Enumerating call spellings catches
    ``hashlib.sha256(...)`` and misses ``__import__("hashlib").sha256(...)``,
    which is the usual fate of a name-matching scan.  So the IMPORT is refused
    as well: nothing in this tree has a legitimate reason to reach a
    stdlib digest — the corpora are transcribed from publications, and AMA's
    own primitives are what the run validates, not what it validates against.
    Neither file imports one today.  That is the same shape
    ``tools/check_stdlib_hash_boundary.py`` applies to the package itself.
    """
    problems: list[str] = []
    scanned = 0
    for root in VECTOR_ROOTS:
        base = repo / root
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*.py")):
            try:
                tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
            except (OSError, SyntaxError) as exc:  # pragma: no cover - unparseable
                problems.append(f"{_rel(path)}: cannot be parsed ({exc})")
                continue
            scanned += 1
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        if alias.name.split(".")[0] in _STDLIB_DIGEST_MODULES:
                            problems.append(
                                f"{_rel(path)}:{node.lineno}: imports {alias.name!r}. "
                                "A vector generator transcribes published values; a "
                                "stdlib digest module here is a second implementation "
                                "in the validation path."
                            )
                    continue
                if isinstance(node, ast.ImportFrom):
                    if (node.module or "").split(".")[0] in _STDLIB_DIGEST_MODULES:
                        problems.append(
                            f"{_rel(path)}:{node.lineno}: imports from "
                            f"{node.module!r}. A vector generator transcribes "
                            "published values; a stdlib digest module here is a "
                            "second implementation in the validation path."
                        )
                    continue
                if not isinstance(node, ast.Call):
                    continue
                if (
                    isinstance(node.func, ast.Name)
                    and node.func.id == "__import__"
                    and node.args
                    and isinstance(node.args[0], ast.Constant)
                    and isinstance(node.args[0].value, str)
                    and node.args[0].value.split(".")[0] in _STDLIB_DIGEST_MODULES
                ):
                    problems.append(
                        f"{_rel(path)}:{node.lineno}: __import__"
                        f"({node.args[0].value!r}) in a vector generator — the same "
                        "rule as a plain import, spelled around it."
                    )
                    continue
                name = _dotted_call_name(node)
                if name in _STDLIB_DIGEST_CALLS:
                    problems.append(
                        f"{_rel(path)}:{node.lineno}: {name}() computes a value in a "
                        "vector generator. On a libcrypto-linked CPython that is "
                        "OpenSSL, so the corpus would record another "
                        "implementation's output as the specification's. "
                        "Transcribe the published value instead."
                    )
    if scanned == 0:
        problems.append(
            "no vector generators found under " + "/, ".join(VECTOR_ROOTS) + "/ — "
            "refusing to report clean having examined nothing"
        )
    return problems


def main() -> int:
    sections = (
        (
            "external cryptographic binaries in " + "/, ".join(SCAN_ROOTS) + "/",
            scan_for_binary_invocations(),
        ),
        ("vendored corpus provenance", scan_corpus_sources()),
        ("reference-encoder independence", check_reference_encoder()),
        ("vector generators compute nothing", scan_vector_generators()),
    )
    failures = [(title, problems) for title, problems in sections if problems]
    for title, problems in sections:
        if not problems:
            print(f"OK    {title}")
    if failures:
        print(
            "\nFAIL: INVARIANT-36 — a third-party cryptographic implementation "
            "is in the validation path.",
            file=sys.stderr,
        )
        for title, problems in failures:
            print(f"  {title}:", file=sys.stderr)
            for problem in problems:
                print(f"    - {problem}", file=sys.stderr)
        return 1
    print(
        "\nINVARIANT-36 holds: AMA is checked against specifications and its own "
        "reference encoder, not against another implementation."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
