#!/usr/bin/env python3
# Copyright (C) 2025-2026 Steel Security Advisors LLC
# SPDX-License-Identifier: Apache-2.0
"""
AMA Cryptography — Ed25519 static precomputation tables (generator)
===================================================================

Emits ``src/c/internal/ama_ed25519_tables.h``: the two base-point tables the
in-tree Ed25519 backend reads at run time, in the affine Niels form
``(y + x, y - x, 2·d·x·y)``, in both limb radices the library compiles the
group arithmetic on.

Two tables
----------
``ama_ed25519_base_comb_<radix>[TABLES][ENTRIES]``
    The fixed-base comb for the constant-time scalar multiplication that
    keygen, sign and ``ama_ed25519_point_from_scalar`` use.  Entry
    ``[k][j]`` is ``(j + 1) · 2^(STRIDE·k) · B`` with ``STRIDE = 2·W`` for a
    signed ``W``-bit window.  Digit ``2k`` of the scalar (weight ``2^(2Wk)``)
    and digit ``2k + 1`` (weight ``2^W`` times that) share table ``k``: the odd
    digits are accumulated first, the accumulator is doubled ``W`` times, and
    the even digits are added.  That halves the table for one extra run of
    ``W`` doublings — Bernstein, Duif, Lange, Schwabe, Yang, "High-speed
    high-security signatures" (2012), §4.

``ama_ed25519_base_odd_<radix>[ODD_COUNT]``
    ``(2i + 1) · B`` for the width-``ODD_WINDOW`` wNAF over the base point in
    the variable-time verify path.  Every verify used to rebuild this table
    from ``B``; it is a function of the curve alone.

Everything is derived from RFC 8032 §5.1: ``p = 2^255 - 19``,
``d = -121665 / 121666``, ``B = (x, 4/5)`` with ``x`` even.  No constant
below is transcribed from any other implementation — the point arithmetic
here is the textbook affine addition law, and the generated header is checked
against the library's own variable-base arithmetic by
``tests/c/test_ed25519_static_tables.c`` and regenerated byte-for-byte by
``tests/test_ed25519_static_tables.py``.

Usage::

    python tools/gen_ed25519_tables.py --write   # regenerate the header
    python tools/gen_ed25519_tables.py --check   # exit 1 if it differs

The output is a pure function of the constants in this file, so ``--check``
is a reproducibility proof, not a formatting check.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Callable, Sequence

REPO_ROOT = Path(__file__).resolve().parent.parent
HEADER_PATH = REPO_ROOT / "src" / "c" / "internal" / "ama_ed25519_tables.h"

#: Field prime and curve constant (RFC 8032 §5.1).
P = 2**255 - 19
D = (-121665 * pow(121666, -1, P)) % P
#: Group order of the base point.
L = 2**252 + 27742317777372353535851937790883648493

#: Signed window width of the fixed-base comb.  Digits are in
#: ``[-2^(W-1), 2^(W-1) - 1]`` after carry recoding, so a table row holds the
#: multiples ``1 .. 2^(W-1)`` (the top digit can reach ``2^(W-1)`` exactly).
COMB_WINDOW = 5
COMB_STRIDE_BITS = 2 * COMB_WINDOW
COMB_ENTRIES = 1 << (COMB_WINDOW - 1)
#: Digits of a 256-bit scalar at width W, and the tables that pair them up.
COMB_DIGITS = -(-256 // COMB_WINDOW)
COMB_TABLES = -(-COMB_DIGITS // 2)

#: wNAF width for the base point in the verify path and the odd multiples it
#: indexes: digits are odd in ``[-(2^(w-1) - 1), 2^(w-1) - 1]`` so only
#: ``|digit| / 2 < 2^(w-2)`` is ever looked up.
ODD_WINDOW = 7
ODD_COUNT = 1 << (ODD_WINDOW - 2)
#: The verify path splits its base-point scalar in two halves of this many
#: bits and walks the second half over the odd multiples of ``2^SHIFT · B``,
#: so both halves share the doublings of one half-length ladder.
ODD_SHIFT = 128

MASK51 = (1 << 51) - 1
MASK64 = (1 << 64) - 1

Point = tuple[int, int]


def _inv(v: int) -> int:
    return pow(v, P - 2, P)


def _sqrt_ratio(u: int, v: int) -> int | None:
    """A square root of ``u / v`` mod p, or None when none exists (RFC 8032 §5.1.3)."""
    x = (u * pow(v, 3, P) * pow(u * pow(v, 7, P) % P, (P - 5) // 8, P)) % P
    if (v * x * x - u) % P == 0:
        return x
    if (v * x * x + u) % P == 0:
        sqrt_m1 = pow(2, (P - 1) // 4, P)
        return (x * sqrt_m1) % P
    return None


def base_point() -> Point:
    """B = (x, 4/5) with the even x (sign bit 0)."""
    y = (4 * _inv(5)) % P
    u = (y * y - 1) % P
    v = (D * y * y + 1) % P
    x = _sqrt_ratio(u, v)
    if x is None:
        raise AssertionError("RFC 8032 base point y = 4/5 must decode")
    if x & 1:
        x = P - x
    return (x, y)


def point_add(p: Point, q: Point) -> Point:
    """Affine twisted-Edwards addition, -x^2 + y^2 = 1 + d x^2 y^2 (complete)."""
    x1, y1 = p
    x2, y2 = q
    x1x2y1y2 = (x1 * x2 % P) * (y1 * y2 % P) % P
    x3 = (x1 * y2 + x2 * y1) * _inv(1 + D * x1x2y1y2) % P
    y3 = (y1 * y2 + x1 * x2) * _inv(1 - D * x1x2y1y2) % P
    return (x3, y3)


def point_mul(k: int, p: Point) -> Point:
    """[k]P by double-and-add.  Public constants only; timing is irrelevant."""
    acc: Point = (0, 1)
    addend = p
    while k > 0:
        if k & 1:
            acc = point_add(acc, addend)
        addend = point_add(addend, addend)
        k >>= 1
    return acc


def on_curve(p: Point) -> bool:
    x, y = p
    return (-x * x + y * y - 1 - D * x * x * y * y) % P == 0


def to_niels(p: Point) -> tuple[int, int, int]:
    x, y = p
    return ((y + x) % P, (y - x) % P, (2 * D * x * y) % P)


def fe51_limbs(v: int) -> list[int]:
    return [(v >> (51 * i)) & MASK51 for i in range(5)]


def fe64_limbs(v: int) -> list[int]:
    return [(v >> (64 * i)) & MASK64 for i in range(4)]


def comb_points() -> list[list[Point]]:
    """comb[k][j] = (j + 1) · 2^(STRIDE·k) · B."""
    b = base_point()
    rows: list[list[Point]] = []
    for k in range(COMB_TABLES):
        base_k = point_mul(1 << (COMB_STRIDE_BITS * k), b)
        rows.append([point_mul(j + 1, base_k) for j in range(COMB_ENTRIES)])
    return rows


def odd_points(shift: int = 0) -> list[Point]:
    """odd[i] = (2i + 1) · 2^shift · B."""
    b = point_mul(1 << shift, base_point())
    return [point_mul(2 * i + 1, b) for i in range(ODD_COUNT)]


def _fmt_limbs(limbs: Sequence[int]) -> str:
    return "{" + ", ".join(f"0x{v:016x}ULL" for v in limbs) + "}"


Limbs = Callable[[int], list[int]]


def _require(condition: bool, message: str) -> None:
    """A generator invariant; a failure here is a bug in this file, not input."""
    if not condition:
        raise RuntimeError(message)


def _fmt_niels(p: Point, limbs_of: Limbs) -> str:
    ypx, ymx, t2d = to_niels(p)
    return (
        "    {"
        + _fmt_limbs(limbs_of(ypx))
        + ",\n     "
        + _fmt_limbs(limbs_of(ymx))
        + ",\n     "
        + _fmt_limbs(limbs_of(t2d))
        + "}"
    )


def _emit_constants(radix: str, limbs_of: Limbs) -> str:
    """d, 2d and sqrt(-1) in the radix's limb form, derived rather than transcribed."""
    sqrt_m1 = pow(2, (P - 1) // 4, P)
    _require((sqrt_m1 * sqrt_m1 + 1) % P == 0, "sqrt(-1) is not a square root of -1")
    return "\n".join(
        [
            "/* d = -121665 / 121666 mod p */",
            f"static const uint64_t ama_ed25519_const_d_{radix}[] = {_fmt_limbs(limbs_of(D))};",
            "/* 2 * d mod p */",
            f"static const uint64_t ama_ed25519_const_d2_{radix}[] = "
            f"{_fmt_limbs(limbs_of((2 * D) % P))};",
            "/* sqrt(-1) = 2^((p - 1) / 4) mod p */",
            f"static const uint64_t ama_ed25519_const_sqrtm1_{radix}[] = "
            f"{_fmt_limbs(limbs_of(sqrt_m1))};",
        ]
    )


def _emit_comb(radix: str, limbs_of: Limbs, rows: list[list[Point]]) -> str:
    out = [
        f"static const ama_ed25519_niels_{radix} "
        f"ama_ed25519_base_comb_{radix}[AMA_ED25519_COMB_TABLES]"
        f"[AMA_ED25519_COMB_ENTRIES] = {{"
    ]
    for k, row in enumerate(rows):
        out.append(f"  {{ /* table {k}: (j+1) * 2^{COMB_STRIDE_BITS * k} * B */")
        out.extend(_fmt_niels(p, limbs_of) + "," for p in row)
        out.append("  },")
    out.append("};")
    return "\n".join(out)


def _emit_odd(radix: str, limbs_of: Limbs, pts: list[Point], shift: int = 0) -> str:
    name = "odd" if shift == 0 else f"odd{shift}"
    base = "B" if shift == 0 else f"2^{shift} * B"
    out = [
        f"static const ama_ed25519_niels_{radix} "
        f"ama_ed25519_base_{name}_{radix}[AMA_ED25519_BASE_ODD_COUNT] = {{"
    ]
    for i, p in enumerate(pts):
        out.append(f"  /* {2 * i + 1} * {base} */")
        out.append(_fmt_niels(p, limbs_of) + ",")
    out.append("};")
    return "\n".join(out)


def render() -> str:
    """The complete header text."""
    b = base_point()
    comb = comb_points()
    odd = odd_points()
    odd_shifted = odd_points(ODD_SHIFT)
    for row in comb:
        for p in row:
            _require(on_curve(p), "a comb entry is not on the curve")
    for p in odd + odd_shifted:
        _require(on_curve(p), "an odd multiple is not on the curve")
    # The first comb entry and the first odd multiple are both B itself.
    _require(comb[0][0] == b and odd[0] == b, "table entry 0 is not B")
    _require(odd_shifted[0] == point_mul(1 << ODD_SHIFT, b), "shifted table entry 0")
    # [L]B is the identity; the tables must be built from a point of order L.
    _require(point_mul(L, b) == (0, 1), "B does not have order L")

    head = f"""/* Copyright (C) 2025-2026 Steel Security Advisors LLC */
/* SPDX-License-Identifier: Apache-2.0 */
/**
 * @file ama_ed25519_tables.h
 * @brief Ed25519 base-point precomputation, affine Niels form, both radices.
 *
 * GENERATED by tools/gen_ed25519_tables.py — do not edit by hand.
 * Regenerate with `python tools/gen_ed25519_tables.py --write`;
 * tests/test_ed25519_static_tables.py fails if this file and the generator
 * disagree, and tests/c/test_ed25519_static_tables.c checks every entry
 * against the library's own variable-base arithmetic.
 *
 * Every point below is derived from the RFC 8032 §5.1 base point
 * B = (x, 4/5) by the affine twisted-Edwards addition law; nothing is
 * transcribed from another implementation.  An entry (y + x, y - x, 2dxy)
 * is the form the mixed addition consumes directly (7 field multiplications
 * per add against an extended-coordinate accumulator).
 *
 * Include with exactly one of AMA_ED25519_TABLES_FE51 (radix 2^51, five
 * limbs) or AMA_ED25519_TABLES_FE64 (radix 2^64, four limbs) defined; each
 * translation unit gets the representation its field arithmetic consumes and
 * nothing else, so no unused table is compiled anywhere.
 *
 * Comb: signed {COMB_WINDOW}-bit window, {COMB_TABLES} tables of {COMB_ENTRIES} entries;
 * table k holds (j + 1) * 2^({COMB_STRIDE_BITS} k) * B for j in [0, {COMB_ENTRIES}).
 * Odd multiples: (2i + 1) * B and (2i + 1) * 2^{ODD_SHIFT} * B for i in [0, {ODD_COUNT}),
 * width-{ODD_WINDOW} wNAF; the second table lets the verify path walk both
 * halves of a base-point scalar in one half-length ladder.
 */
#ifndef AMA_ED25519_TABLES_H
#define AMA_ED25519_TABLES_H

#include <stdint.h>

#define AMA_ED25519_COMB_WINDOW      {COMB_WINDOW}
#define AMA_ED25519_COMB_STRIDE_BITS {COMB_STRIDE_BITS}
#define AMA_ED25519_COMB_ENTRIES     {COMB_ENTRIES}
#define AMA_ED25519_COMB_DIGITS      {COMB_DIGITS}
#define AMA_ED25519_COMB_TABLES      {COMB_TABLES}
#define AMA_ED25519_BASE_ODD_WINDOW  {ODD_WINDOW}
#define AMA_ED25519_BASE_ODD_COUNT   {ODD_COUNT}
#define AMA_ED25519_BASE_ODD_SHIFT   {ODD_SHIFT}

/* Instantiated by defining exactly one of AMA_ED25519_TABLES_FE51 /
 * AMA_ED25519_TABLES_FE64 before inclusion.  Defining both is a real
 * misuse and is rejected; defining neither (a standalone analysis pass)
 * leaves this header as constants only, a clean no-op. */
#if defined(AMA_ED25519_TABLES_FE51) && defined(AMA_ED25519_TABLES_FE64)
#error "define at most one of AMA_ED25519_TABLES_FE51 / AMA_ED25519_TABLES_FE64"
#endif
"""
    fe51 = "\n".join(
        [
            "",
            "#if defined(AMA_ED25519_TABLES_FE51)",
            "",
            "typedef struct {",
            "    uint64_t ypx[5];",
            "    uint64_t ymx[5];",
            "    uint64_t t2d[5];",
            "} ama_ed25519_niels_fe51;",
            "",
            _emit_constants("fe51", fe51_limbs),
            "",
            _emit_comb("fe51", fe51_limbs, comb),
            "",
            _emit_odd("fe51", fe51_limbs, odd),
            "",
            _emit_odd("fe51", fe51_limbs, odd_shifted, ODD_SHIFT),
            "",
            "#endif /* AMA_ED25519_TABLES_FE51 */",
        ]
    )
    fe64 = "\n".join(
        [
            "",
            "#if defined(AMA_ED25519_TABLES_FE64)",
            "",
            "typedef struct {",
            "    uint64_t ypx[4];",
            "    uint64_t ymx[4];",
            "    uint64_t t2d[4];",
            "} ama_ed25519_niels_fe64;",
            "",
            _emit_constants("fe64", fe64_limbs),
            "",
            _emit_comb("fe64", fe64_limbs, comb),
            "",
            _emit_odd("fe64", fe64_limbs, odd),
            "",
            _emit_odd("fe64", fe64_limbs, odd_shifted, ODD_SHIFT),
            "",
            "#endif /* AMA_ED25519_TABLES_FE64 */",
        ]
    )
    return head + fe51 + "\n" + fe64 + "\n\n#endif /* AMA_ED25519_TABLES_H */\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="write the header")
    group.add_argument("--check", action="store_true", help="exit 1 if the header differs")
    parser.add_argument(
        "--output",
        type=Path,
        default=HEADER_PATH,
        help=f"header path (default: {HEADER_PATH.relative_to(REPO_ROOT)})",
    )
    args = parser.parse_args(argv)

    text = render()
    if args.write:
        args.output.write_text(text, encoding="utf-8", newline="")
        print(f"wrote {args.output} ({len(text)} bytes)")
        return 0
    if not args.output.is_file():
        print(f"MISSING: {args.output}", file=sys.stderr)
        return 1
    current = args.output.read_bytes().decode("utf-8")
    if current != text:
        print(f"STALE: {args.output} differs from the generator output", file=sys.stderr)
        return 1
    print(f"OK: {args.output} matches the generator ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
